In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_parquet("customer.parquet", engine="fastparquet")

In [3]:
df["Mobile"] = df["Mobile"].str.zfill(10)

In [4]:
df.to_parquet("../data/01_raw/raw_customers.parquet", engine="fastparquet", index=False)

In [2]:
df = pd.read_parquet("customer.parquet", engine="fastparquet")

In [3]:
df.head()

,CustomerID,CreationOn,ModifiedOn,UserTitle,CustomerName,Mobile,Mobile2,Email,Gender,Nationality,BirthDate,LocationName,IsOwner,IsCashCustomer,PayTerm,Age,IsActive,StationBrand
0,EB5670AA-72D8-49CE-8FAC-00000859EB85,2021-03-12 00:11:18,2020-03-26 11:55:24,None,ABU RAKAN,0555551397,None,None,None,None,None,None,True,True,None,NaN,True,PE
1,4C86E939-005E-4611-B4C1-00000A03F8CA,2021-03-12 00:11:18,2020-03-26 11:55:24,None,MR OLAYYAN,0547502121,None,None,None,None,None,None,True,True,None,NaN,True,PE
2,F6090720-12AA-4DC3-BA2A-00001D49C2DC,2021-03-12 00:11:18,2020-03-26 11:55:24,None,MR.AWAD,0534077960,None,None,None,None,None,None,True,True,None,NaN,True,PE
3,5E65098C-E166-466D-9309-000022944B45,2021-03-12 00:11:18,2020-03-26 11:55:24,None,MR. MOHAMAD MOBARAK DOSERI,0546919905,None,None,None,None,None,None,True,True,None,NaN,True,PE
4,E6E57568-A4F0-4A0D-95DD-00002CA50962,2021-03-12 00:11:18,2020-03-26 11:55:24,None,MR.ALI,0503814721,None,None,None,None,None,None,True,True,None,NaN,True,PE

In [11]:
filter_cash = df["IsCashCustomer"] == True
filter_owner = df["IsOwner"] == True
(df["IsOwner"] == True).astype(int).mean()

0.6840337032988161

In [7]:
df["age_group"] = pd.cut(df["Age"], bins=[0, 20, 30, 40, 50, 60, np.PINF], labels=["0-20", "21-30", "31-40", "41-50", "51-60", "60+"])

In [8]:
df.isna().mean()

CustomerID        0.000000
CreationOn        0.000000
ModifiedOn        0.000000
UserTitle         0.763020
CustomerName      0.000000
Mobile            0.000000
Mobile2           0.994761
Email             0.998979
Gender            0.603676
Nationality       0.652246
BirthDate         0.997381
LocationName      0.716974
IsOwner           0.000000
IsCashCustomer    0.000000
PayTerm           0.999888
Age               0.769007
IsActive          0.000000
StationBrand      0.000000
age_group         0.774785
dtype: float64

In [9]:
df["Mobile"] = df["Mobile"].str.zfill(10)
df["Mobile"] = df["Mobile"].str.slice_replace(stop=1, repl='966')

In [10]:
df.head()

,CustomerID,CreationOn,ModifiedOn,UserTitle,CustomerName,Mobile,Mobile2,Email,Gender,Nationality,BirthDate,LocationName,IsOwner,IsCashCustomer,PayTerm,Age,IsActive,StationBrand,age_group
0,EB5670AA-72D8-49CE-8FAC-00000859EB85,2021-03-12 00:11:18,2020-03-26 11:55:24,None,ABU RAKAN,966555551397,None,None,None,None,None,None,True,True,None,NaN,True,PE,NaN
1,4C86E939-005E-4611-B4C1-00000A03F8CA,2021-03-12 00:11:18,2020-03-26 11:55:24,None,MR OLAYYAN,966547502121,None,None,None,None,None,None,True,True,None,NaN,True,PE,NaN
2,F6090720-12AA-4DC3-BA2A-00001D49C2DC,2021-03-12 00:11:18,2020-03-26 11:55:24,None,MR.AWAD,966534077960,None,None,None,None,None,None,True,True,None,NaN,True,PE,NaN
3,5E65098C-E166-466D-9309-000022944B45,2021-03-12 00:11:18,2020-03-26 11:55:24,None,MR. MOHAMAD MOBARAK DOSERI,966546919905,None,None,None,None,None,None,True,True,None,NaN,True,PE,NaN
4,E6E57568-A4F0-4A0D-95DD-00002CA50962,2021-03-12 00:11:18,2020-03-26 11:55:24,None,MR.ALI,966503814721,None,None,None,None,None,None,True,True,None,NaN,True,PE,NaN

In [14]:
df_no_dup = df[df["IsActive"] == True].sort_values(["ModifiedOn", "CustomerID"]).drop_duplicates(["Mobile"], keep="last")
df_no_dup.to_csv("../../customer_info_20250501.csv", sep=";")