In [56]:
import numpy as np
import pandas as pd

In [57]:
branch_df = pd.read_parquet("branch.parquet", engine="fastparquet")
vehicle_df = pd.read_parquet("vehicle.parquet", engine="fastparquet")
customer_df = pd.read_parquet("customer.parquet", engine="fastparquet")

In [58]:
branch_df.to_parquet("branches.parquet", engine="fastparquet", index=False)
vehicle_df.to_parquet("vehicles.parquet", engine="fastparquet", index=False)
customer_df.to_parquet("customers.parquet", engine="fastparquet", index=False)

In [26]:
display(branch_df.head())
display(vehicle_df.head())
display(customer_df.head())

,BranchID,BranchCode,BranchType,IsActive,BranchName,AMBadgeNo,AreaManager,Region,RMBadgeNo,RegionalManager,Longitude,Latitude,City,StationBrand
0,4BC3ADA4-5793-4026-B2A6-2C14ABAD2305,1884,PE,False,TRISTAR DAMMAM,None,None,PAC,None,None,NaN,NaN,DAMMAM,PE
1,92DB0871-73E5-423A-AE8B-2E49A2A52058,1583,PE,False,ALDRESS MAROOJ,None,None,CR NORTH,None,None,NaN,NaN,RIYADH,PE
2,F5DD72D1-D6EA-4C45-989C-3499BF156D25,1508,PE,False,TASHHEED AL RIYADH,None,None,CR EAST,None,None,NaN,NaN,RIYADH,PE
3,429D8BE2-F6DC-45D4-8B52-43CF2E6B654D,1119,PE,False,ZTAMWAJ,None,None,SOUTHERN REGION,None,None,NaN,NaN,ABHA,PE
4,0B5F67FA-1D34-42E1-825D-454AF1365037,2089_ToDex,Diesel,False,Well Qassim-Riyadh-Al Atsh,None,None,None,None,None,25.525793,45.946956,None,PE

,CustomerVehicleID,CreationOn,ModifiedOn,CustomerID,Make,Model,ModelYear,TransmissionType,PMSName,PlateNumber,VIN,IsDriverOwner,StationBrand
0,918FE112-E062-4A56-8033-000001BFCEC6,2021-03-12 00:11:44,2020-03-26 11:55:24,40AA5E88-1966-4494-B3FE-54112BF3F479,CHEVROLET,SUBURBAN,2013.0,Automatic,None,5340AAJ,1GNSC8E07DR219313,False,PE
1,1B4AA1DD-1E18-4990-AB45-000002BF3307,2021-03-12 00:11:44,2020-03-26 11:55:24,E1EAFA23-0ADC-4AFA-A774-4E27CDA23AA9,LEXUS,LS400,1998.0,Automatic,TOYOTA,0068LAZ,JTB530F20W0115484,False,PE
2,8752306B-7FD4-4ABB-8E52-00002A049E37,2021-03-12 00:11:44,2020-03-26 11:55:24,22B51812-64A4-44F1-A5AD-F6850639C800,TOYOTA,HILLUX,2016.0,Automatic,TOYOTA,8412SBB,MR0HX8CD3G0902343,False,PE
3,CECB08B1-73B0-44A7-B19F-00002BE80CC8,2021-03-12 00:11:44,2020-03-26 11:55:24,C54F5632-2621-4BD5-8040-6CF1A92BA3DA,HYUNDAI,ACCENT,2009.0,Automatic,HYUNDAI,9261RKA,KMHCM41A89U326551,False,PE
4,286358CB-BE12-40D8-A428-0000425C16D7,2021-03-12 00:11:44,2020-03-26 11:55:24,7B7E7432-17D1-4F57-BE02-D0CD61CEE722,HYUNDAI,Elantra,2017.0,Automatic,HYUNDAI,4470UAD,KMHD741F4HU156825,False,PE

,CustomerID,CreationOn,ModifiedOn,UserTitle,CustomerName,Mobile,Mobile2,Email,Gender,Nationality,BirthDate,LocationName,IsOwner,IsCashCustomer,PayTerm,Age,IsActive,StationBrand
0,EB5670AA-72D8-49CE-8FAC-00000859EB85,2021-03-12 00:11:18,2020-03-26 11:55:24,None,ABU RAKAN,0555551397,None,None,None,None,NaN,None,True,True,None,NaN,True,PE
1,4C86E939-005E-4611-B4C1-00000A03F8CA,2021-03-12 00:11:18,2020-03-26 11:55:24,None,MR OLAYYAN,0547502121,None,None,None,None,NaN,None,True,True,None,NaN,True,PE
2,F6090720-12AA-4DC3-BA2A-00001D49C2DC,2021-03-12 00:11:18,2020-03-26 11:55:24,None,MR.AWAD,0534077960,None,None,None,None,NaN,None,True,True,None,NaN,True,PE
3,5E65098C-E166-466D-9309-000022944B45,2021-03-12 00:11:18,2020-03-26 11:55:24,None,MR. MOHAMAD MOBARAK DOSERI,0546919905,None,None,None,None,NaN,None,True,True,None,NaN,True,PE
4,E6E57568-A4F0-4A0D-95DD-00002CA50962,2021-03-12 00:11:18,2020-03-26 11:55:24,None,MR.ALI,0503814721,None,None,None,None,NaN,None,True,True,None,NaN,True,PE

In [27]:
pd.merge(
    customer_df.drop(columns=["CreationOn", "ModifiedOn"]),
    vehicle_df.drop(columns=["CreationOn", "ModifiedOn"]),
    on="CustomerID"
).head()

,CustomerID,UserTitle,CustomerName,Mobile,Mobile2,Email,Gender,Nationality,BirthDate,LocationName,...,CustomerVehicleID,Make,Model,ModelYear,TransmissionType,PMSName,PlateNumber,VIN,IsDriverOwner,StationBrand_y
0,EB5670AA-72D8-49CE-8FAC-00000859EB85,None,ABU RAKAN,0555551397,None,None,None,None,NaN,None,...,04DF1357-3211-4FDD-99F3-6B57B49D9181,TOYOTA,AURION,2009.0,Automatic,TOYOTA,3280SGA,6T1BK40K29X922477,False,PE
1,4C86E939-005E-4611-B4C1-00000A03F8CA,None,MR OLAYYAN,0547502121,None,None,None,None,NaN,None,...,165ABEC7-0E8A-4BA9-8D73-16CE1C8767B6,CADILLAC,ESCALADE,2011.0,Automatic,None,1618LGA,1618LGA,False,PE
2,F6090720-12AA-4DC3-BA2A-00001D49C2DC,None,MR.AWAD,0534077960,None,None,None,None,NaN,None,...,3CC2FEAC-976D-4C80-9836-ADCECBCEB3E1,TOYOTA,HILUX,2010.0,Automatic,TOYOTA,5851EEA,MR0AX12G7A0043270,False,PE
3,5E65098C-E166-466D-9309-000022944B45,None,MR. MOHAMAD MOBARAK DOSERI,0546919905,None,None,None,None,NaN,None,...,97E26457-EDF2-4E3E-8DA4-84B492604A13,FORD,EXPEDITION,2006.0,Automatic,None,2500ZUA,1FMPU15536LA74271,False,PE
4,E6E57568-A4F0-4A0D-95DD-00002CA50962,None,MR.ALI,0503814721,None,None,None,None,NaN,None,...,BA9C8E25-C41B-4093-A2A8-09E183A71F96,FORD,CROWN VICTORIA,2010.0,Automatic,None,7291SJB,2FABP7CW3AX130294,False,PE

In [28]:
print(vehicle_df.shape)
vehicles_cols = set(vehicle_df.columns) - set(["StationBrand"])
vehicle_df = vehicle_df.drop_duplicates(subset=vehicles_cols, keep="first")
print(vehicle_df.shape)

(7005372, 13)
(6977130, 13)

In [41]:
vehicle_df["VIN"] = np.where(vehicle_df["VIN"].astype(str).str.len() != 17, np.nan, vehicle_df["VIN"])
vehicle_df["VIN"] = np.where(
    (vehicle_df["VIN"].isnull()) & (vehicle_df["PlateNumber"].astype(str).str.len() == 17),
    vehicle_df["PlateNumber"],
    vehicle_df["VIN"]
)
vehicle_df["PlateNumber"] = np.where(vehicle_df["PlateNumber"].astype(str).str.len() < 6, np.nan, vehicle_df["PlateNumber"])
vehicle_df["PlateNumber"] = np.where(vehicle_df["PlateNumber"].astype(str).str.len() > 7, np.nan, vehicle_df["PlateNumber"])

In [42]:
vehicle_df.head()

,CustomerVehicleID,CreationOn,ModifiedOn,CustomerID,Make,Model,ModelYear,TransmissionType,PMSName,PlateNumber,VIN,IsDriverOwner,StationBrand
0,918FE112-E062-4A56-8033-000001BFCEC6,2021-03-12 00:11:44,2020-03-26 11:55:24,40AA5E88-1966-4494-B3FE-54112BF3F479,CHEVROLET,SUBURBAN,2013.0,Automatic,None,5340AAJ,1GNSC8E07DR219313,False,PE
1,1B4AA1DD-1E18-4990-AB45-000002BF3307,2021-03-12 00:11:44,2020-03-26 11:55:24,E1EAFA23-0ADC-4AFA-A774-4E27CDA23AA9,LEXUS,LS400,1998.0,Automatic,TOYOTA,0068LAZ,JTB530F20W0115484,False,PE
2,8752306B-7FD4-4ABB-8E52-00002A049E37,2021-03-12 00:11:44,2020-03-26 11:55:24,22B51812-64A4-44F1-A5AD-F6850639C800,TOYOTA,HILLUX,2016.0,Automatic,TOYOTA,8412SBB,MR0HX8CD3G0902343,False,PE
3,CECB08B1-73B0-44A7-B19F-00002BE80CC8,2021-03-12 00:11:44,2020-03-26 11:55:24,C54F5632-2621-4BD5-8040-6CF1A92BA3DA,HYUNDAI,ACCENT,2009.0,Automatic,HYUNDAI,9261RKA,KMHCM41A89U326551,False,PE
4,286358CB-BE12-40D8-A428-0000425C16D7,2021-03-12 00:11:44,2020-03-26 11:55:24,7B7E7432-17D1-4F57-BE02-D0CD61CEE722,HYUNDAI,Elantra,2017.0,Automatic,HYUNDAI,4470UAD,KMHD741F4HU156825,False,PE

In [47]:
vehicle_df["CustomerVehicleID"].shape, vehicle_df["CustomerVehicleID"].nunique(), vehicle_df["VIN"].dropna().shape[0], vehicle_df["VIN"].dropna().nunique(), vehicle_df["PlateNumber"].dropna().shape[0], vehicle_df["PlateNumber"].dropna().nunique()

((6977130,), 6977130, 6514810, 5604707, 6878853, 5674635)

In [45]:
vehicle_df[vehicle_df["PlateNumber"].astype(str).str.len() == 6]["PlateNumber"]

195        392755
1127       759973
1325       405966
1648       211308
1931       A77009
            ...
6977048    633ART
6977066    256278
6977081    458DZJ
6977093    184767
6977103    204VDN
Name: PlateNumber, Length: 117724, dtype: object

In [51]:
vehicle_df[vehicle_df["PlateNumber"] == "2962HBB"]

,CustomerVehicleID,CreationOn,ModifiedOn,CustomerID,Make,Model,ModelYear,TransmissionType,PMSName,PlateNumber,VIN,IsDriverOwner,StationBrand
2270258,02B568CF-EC21-4C4F-B163-1F148465CC07,2021-03-12 00:11:44,2020-10-13 18:13:03,6E47489B-349E-45E4-A2DB-8FCDDF90C509,NISSAN,URVAN,2016.0,Manual,NISSAN,2962HBB,JN6CE6BS3G9000206,False,PE
2276225,7A2CC12F-434B-4FFA-9D9F-4FA72910EB2D,2021-03-12 00:11:44,2020-10-13 18:13:03,5D8362CC-DEA5-4947-8B9D-C9460B78259E,NISSAN,Urvan E26,2016.0,Manual,NISSAN,2962HBB,JN6CE6BS3G9000206,False,PE
2283756,EE9C2610-9B35-4DA0-A187-8D49D0EB0B81,2021-03-12 00:11:44,2020-10-13 18:13:03,B6C9C1C7-3AC8-457B-9539-43CC1EAC9836,NISSAN,Urvan E26,2016.0,Manual,NISSAN,2962HBB,JN6CE6BS3G9000206,False,PE
2287692,E6C3B3AA-7B44-4062-8294-ABB78BFDA8AD,2021-03-12 00:11:44,2020-10-01 16:25:18,1A79A0F1-038A-4E8C-9C25-61B2A1F13572,NISSAN,URVAN,2016.0,Manual,NISSAN,2962HBB,JN6CE6BS3G9000206,False,PE
2287888,7D52FA7E-99D0-4A91-B061-ADE1445EB732,2021-03-12 00:11:44,2020-10-01 16:25:18,C4C8F40C-A090-4BE8-81D1-8D28C43EB9F1,NISSAN,URVAN,2015.0,Manual,None,2962HBB,JN6CE6BS3G9000206,False,PE
2288221,296A76D4-6A4F-4275-9341-B152596D0CB8,2021-03-12 00:11:44,2020-10-13 18:13:03,CCB32251-0D51-419F-9796-77DDEAD636DE,NISSAN,URVAN,2016.0,Manual,NISSAN,2962HBB,JN6CE6BS3G9000206,False,PE
2288433,710DAC38-37F1-4AB5-9E3A-B3400C57B90B,2021-03-12 00:11:44,2020-10-13 18:13:03,BFA435B0-B31B-4F2D-AF7D-01025E71CA91,NISSAN,Urvan E26,2016.0,Manual,None,2962HBB,JN6CE6BS3G9000209,False,PE
2288988,7F02AEF3-5C9C-48D5-A156-B7C22A2E5CCF,2021-03-12 00:11:44,2020-10-01 16:25:18,01649475-4F1D-4190-ABD7-E9986F3FB3C1,NISSAN,URVAN,2018.0,Manual,NISSAN,2962HBB,JN6CE6BS3G9000206,False,PE
2289559,E4D5D2A7-D6BC-4A21-A4A0-BB66F82BC5B8,2021-03-12 00:11:44,2020-10-01 16:25:18,94AACBEB-FF8D-42D8-853D-3180F0DEFDFC,NISSAN,URVAN,2016.0,Manual,NISSAN,2962HBB,JN6CE6BS3G9000206,False,PE
2291025,02C3E131-F7C5-4640-95E3-C7024A8651D0,2021-03-12 00:11:44,2020-10-13 18:13:03,D0339592-3749-4992-89DA-6F175A27B5A8,NISSAN,URVAN,2016.0,Manual,NISSAN,2962HBB,JN6CE6BS3G9000209,False,PE
3404220,0ACBEAEF-3C3C-418B-AE7D-76FF20B57A36,2021-03-12 00:11:44,2021-06-04 19:05:07,7B014465-6C47-4EA9-965B-20BB8E3B927F,NISSAN DIESEL,URVAN (E26) DIESEL,2016.0,Manual,None,2962HBB,JN6CE6BS3G9000206,False,PE
3446930,177F24F5-6C68-4BA3-AB57-7DDF8199CAA4,2021-03-12 00:11:44,2021-06-04 19:05:07,50B0A8C9-B2FB-4055-9CD1-2BE77D858B32,NISSAN,URVAN,2016.0,Manual,NISSAN,2962HBB,JN6CE6BS3G9000206,False,PE
3662210,D1DCA1D4-BB5B-4AE4-A931-9D7CDD14A580,2021-03-12 00:11:44,2021-06-04 19:05:07,5F688C08-D8A8-4E60-88C3-BDD6E421F1CA,NISSAN,URVAN,2016.0,Manual,None,2962HBB,JN6CE6BS3G9000206,False,PE
6393223,90547407-1919-450E-A32F-AB7414080303,2024-06-10 18:19:28,2024-06-10 19:14:26,9DC7F67C-BBA4-43F3-AF4B-4F98BCF1C60F,NISSAN,Urvan E26,2016.0,Manual,NISSAN,2962HBB,JN6CE6BS3G9000209,True,PE
6409293,61385A99-9265-41CB-AD64-F14722AEF0E5,2024-06-10 18:06:00,2024-06-28 21:19:43,FD5F38F5-6F63-4161-A3D0-85B5C8D3C838,NISSAN,URVAN,2016.0,Manual,NISSAN,2962HBB,JN6CE6BS3G9000209,False,PE
6495683,132A443D-F95E-4908-8979-ED27A41462E5,2021-08-01 19:42:05,2024-07-29 19:46:21,15D5AEC7-1C5D-40B7-BD48-B71EDFDAA16E,NISSAN,Urvan E26,2016.0,Manual,NISSAN,2962HBB,JN6CE6BS3G9000209,False,PE

In [52]:
customer_df[customer_df["CustomerID"] == "9DC7F67C-BBA4-43F3-AF4B-4F98BCF1C60F"]

,CustomerID,CreationOn,ModifiedOn,UserTitle,CustomerName,Mobile,Mobile2,Email,Gender,Nationality,BirthDate,LocationName,IsOwner,IsCashCustomer,PayTerm,Age,IsActive,StationBrand
5711993,9DC7F67C-BBA4-43F3-AF4B-4F98BCF1C60F,2024-06-10 18:19:28,2024-06-10 19:14:26,None,M,0505118074,None,None,Male,None,NaN,None,False,True,None,NaN,True,PE

In [53]:
customer_df[customer_df["CustomerID"] == "FD5F38F5-6F63-4161-A3D0-85B5C8D3C838"]

,CustomerID,CreationOn,ModifiedOn,UserTitle,CustomerName,Mobile,Mobile2,Email,Gender,Nationality,BirthDate,LocationName,IsOwner,IsCashCustomer,PayTerm,Age,IsActive,StationBrand
5729158,FD5F38F5-6F63-4161-A3D0-85B5C8D3C838,2024-06-10 18:06:00,2024-06-28 21:19:43,None,MOHAMMAD MOHASSAIN,0566605764,None,None,Male,Yemeni,NaN,None,False,True,None,NaN,True,PE

In [55]:
customer_df[customer_df["CustomerID"] == "6E47489B-349E-45E4-A2DB-8FCDDF90C509"]

,CustomerID,CreationOn,ModifiedOn,UserTitle,CustomerName,Mobile,Mobile2,Email,Gender,Nationality,BirthDate,LocationName,IsOwner,IsCashCustomer,PayTerm,Age,IsActive,StationBrand
3219844,6E47489B-349E-45E4-A2DB-8FCDDF90C509,2021-03-12 00:11:18,2020-10-13 18:13:03,Mr.,WAKAS,0551835339,None,None,Male,None,NaN,None,False,True,None,NaN,True,PE

In [50]:
vehicle_df["PlateNumber"].value_counts()[:50]

PlateNumber
2222BBB    159
1111AAA     97
2222JJJ     72
1234ABJ     64
0123ABC     48
1111BBB     47
1234AAA     26
0000AAA     25
2222AAA     22
0022BBB     22
4444AAA     21
2222SSS     21
1234ABC     20
2194VBB     20
NOPLATE     20
2222XXX     18
2962HBB     16
6163NHA     16
3422GBB     15
111AAA      15
2222DDD     15
1234ABD     15
1904LLD     15
3208JKD     14
8334BRB     14
9314ZXD     14
1098KBD     14
5555SSS     14
9532JSA     14
2151SAS     14
3856NBB     13
1111SSS     13
4938GLA     13
4939GLA     13
2181NJB     13
1962VKB     13
1757SDB     13
1635UDA     13
5092XDD     13
3430HNA     13
7434HBB     13
5584DDB     13
7782ULD     13
6940TJD     12
8237TDB     12
5555HHH     12
2614THA     12
2013VUA     12
7877DUA     12
5114DUA     12
Name: count, dtype: int64