# Imports

In [1]:
import pyspark
from typing import List, Union, Dict
import pyspark.sql.functions as f
from dateutil.relativedelta import relativedelta
from pyspark.sql.window import Window
import pandas as pd
import scipy.sparse as sp
from implicit.als import AlternatingLeastSquares
from pyspark import SparkConf
from pyspark.sql import SparkSession

/Users/Andre_Barbosa/anaconda3/envs/petromin/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [ ]:
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)

In [2]:
parameters = {
    "spark.driver.maxResultSize": "50g",
    "spark.hadoop.fs.s3a.impl": "org.apache.hadoop.fs.s3a.S3AFileSystem",
    "spark.sql.execution.arrow.pyspark.enabled": True,

    # https://docs.kedro.org/en/stable/integrations/pyspark_integration.html#tips-for-maximising-concurrency-using-threadrunner
    "spark.scheduler.mode": "FAIR",
    "spark.driver.extraJavaOptions": "-Djava.security.manager=allow -Dio.netty.tryReflectionSetAccessible=true",
    "spark.executor.extraJavaOptions": "-Djava.security.manager=allow -Dio.netty.tryReflectionSetAccessible=true",

    "spark.sql.legacy.parquet.nanosAsLong": True,
    "spark.sql.legacy.timeParserPolicy": "LEGACY",
    "spark.driver.memory": "50g",
}

spark_conf = SparkConf().setAll(parameters.items())

In [3]:
spark = SparkSession.builder.appName('New').enableHiveSupport().config(conf=spark_conf).getOrCreate()

Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
25/05/02 11:40:59 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable

## Load data

In [4]:
int_transactions = spark.read.parquet("../data/02_intermediate/int_transactions")
prm_spine = spark.read.parquet("../data/03_primary/prm_spine")

In [110]:
categories_to_drop = []
categories_to_keep = []
sectors_to_drop = []
sectors_to_drop_additional = []
products_to_drop = []


initial_date = initial_date_nptb_pull = '2023-01-01'
n_quarter_nptb_pull = 4
n_recommendations_pull = 10
min_number_of_trx_for_recommendations = 3

n_quarter_nptb_push = 6
last_date = "2025-01-01" # First date of predictions
minimum_orders_to_be_considered = 2
products_to_drop_push = [
    "SERVICE CHARGES 10 SAR | SERVICE | SERVICE"
]

als_params = {
    "factors": 3,
    "regularization": 0.08,
    "alpha": 0.17,
    "random_state": 123,
}
recommendations_per_user = 10

# Pull

## Clean transactions

In [ ]:
sectors_to_drop = list(set(sectors_to_drop).union(set(sectors_to_drop_additional)))
relevant_ids = master.filter(
    ~master.sector_id_original.isin(sectors_to_drop)
).select(
    f.col('_id').alias('client_id')
).dropDuplicates()
transactions = transactions.join(relevant_ids, on='client_id', how='inner')
transactions = transactions.filter(
    ~(
    ((f.col('transaction_typ')=='FA') & (f.col('total_product_val')<=0))|
    (f.col('total_catalog_product_val')<f.col('total_product_val'))
    )
)

products = products.withColumn(
    "category_name",
    f.regexp_replace(f.lower(f.col("category_name")), ' ', '_')
).drop('product_name')

products = products.filter(~f.col('product_id').isin(products_to_drop))

transactions = transactions.join(
    products,
    on=["product_id"],
    how="left"
)
categories_to_drop = list(set(categories_to_drop)-set(categories_to_keep))
transactions = transactions.withColumn(
    'category_name',
    f.when(
        (f.col('category_name')=='premios') & 
        ((f.col('total_product_val')>1) | (f.col('total_catalog_product_val')>1)),
        f.lit('others')
    ).otherwise(f.col('category_name'))
)
transactions = transactions.filter(~f.col('category_name').isin(categories_to_drop))
transactions = transactions.withColumn('year_month', f.col('transaction_dt').substr(0,7))

## Prepare transactions

In [ ]:
initial_date_n_months_before = (pd.to_datetime(initial_date) + pd.offsets.MonthEnd(0)) - relativedelta(months=n_months_nptb_pull)

transactions = transactions.withColumn(
    'transaction_month', 
    f.last_day('transaction_dt')
).filter(
    f.col('transaction_month') >= initial_date_n_months_before
).select(
    'transaction_month',
    'client_id',
    'product_id',
    'product_name',
    'product_qty',
    'total_product_val',
    'total_catalog_product_val'
).groupBy(
    ['transaction_month', 'client_id', 'product_id', 'product_name']
).agg(
    f.sum('product_qty').alias('product_qty'),
    f.sum('total_product_val').alias('total_product_val'),
    f.sum('total_catalog_product_val').alias('total_catalog_product_val')
)

out = transactions.orderBy(['client_id', 'product_id','transaction_month'])

In [ ]:
initial_date_n_months_before = pd.to_datetime(initial_date) - relativedelta(months=n_quarter_nptb_pull * 3)

In [99]:
int_transactions = int_transactions.withColumn(
    "_id", 
    f.concat_ws("__", *["customer_id", "customer_vehicle_id"])
).withColumn(
    "_observ_end_dt",
    f.to_date(f.date_trunc("quarter", f.col("transaction_dt")))
)

base_transactions = prm_spine.join(
    int_transactions,
    on=["_id", "_observ_end_dt"],
    how="inner"
)

In [ ]:
transactions = base_transactions.filter(
    f.col("_observ_end_dt") >= initial_date_n_months_before
).select(
    "_observ_end_dt",
    "_id",
    "customer_id",
    "customer_vehicle_id",
    "product_category",
    "product_id",
    "quantity",
    "sales_amount_net",
    "total_profit",
).groupBy(
    "_observ_end_dt", "_id", "customer_id", "customer_vehicle_id", "product_category", "product_id",
).agg(
    f.sum('quantity').alias('product_qty'),
    f.sum('sales_amount_net').alias('total_product_val'),
    f.sum('total_profit').alias('total_profit_product_val')
).orderBy("_id", "product_category", "product_id", "_observ_end_dt")

## Create features

In [72]:
window_client_product = Window.partitionBy(['_id', 'product_id']).orderBy(f.col("_observ_end_dt"))
window_client = Window.partitionBy(['_id']).orderBy(f.col("_observ_end_dt"))

date_range = prm_spine.select('_observ_end_dt').distinct().orderBy('_observ_end_dt')
min_date_per_client = transactions.groupby('_id', 'product_id').agg(f.min('_observ_end_dt').alias('first_trx_dt'))

max_date = date_range.agg({"_observ_end_dt": "max"}).collect()[0]["max(_observ_end_dt)"]

new_month = date_range.filter(
    date_range._observ_end_dt==max_date
).withColumn(
    '_observ_end_dt',
    f.add_months(f.col('_observ_end_dt'), 3)
)

new_date = new_month.agg({"_observ_end_dt": "max"}).collect()[0]["max(_observ_end_dt)"]


date_range = date_range.union(new_month).orderBy('_observ_end_dt')

In [74]:
client_sku = transactions.select(['_id', 'product_id',]).distinct()
client_sku_first_dt = client_sku.join(min_date_per_client, on=['_id', 'product_id'], how='inner')

sku_date_crossjoin = client_sku_first_dt.crossJoin(
    f.broadcast(date_range)
).filter(
    f.col('_observ_end_dt') >= f.col('first_trx_dt')
).drop('first_trx_dt')

transactions_after_fst_trx = transactions.join(
    sku_date_crossjoin,
    on=['_id', 'product_id', '_observ_end_dt'],
    how='right'
)

In [ ]:
working_ids = [
    # "00000540-7986-4B85-A946-E1A9D913344F__F40BF538-A9A6-49E3-9623-9301AE9FD953",
    "00000847-CECD-43FB-A2F9-4D4B44A8BFFC__FF645321-C6D1-4864-91B7-F00EA37C30DB",
    "00000E2B-FD56-4F34-A54C-159E564F5F79__FF8A2477-4270-4547-B4CB-5706EA4479A0", ## 
    "D7185FBD-201B-49A3-B8F7-67A48705CF4A__741EBA32-9096-4557-B3AF-216AFB616384",
    "51392616-9B76-4435-8C0E-43C0139BCA1F__7272896E-F429-47A5-88F8-1195CE25FB9D",
    "AF8F3733-EE8E-493C-AD23-2F15BF80CF16__151779EE-F4CE-4F5B-9430-393D04006AAE",
    "FAB53EBC-173F-42EA-BC1F-BE6A860E5C3C__8DEE90FD-3BD0-40B4-9373-9E019AFE6BBC",
]

In [84]:
transactions_per_client = transactions_after_fst_trx.groupBy(
    ['_id', '_observ_end_dt']
).agg(
    f.sum('total_product_val').alias('total_client_net_sales'),
    f.sum('total_profit_product_val').alias('total_client_profit_sales')
).withColumn(
    'placed_order', 
    f.when(f.col('total_client_net_sales')>0,1).otherwise(0)
).withColumn(
    'total_client_orders_last_quarters',
    f.sum('placed_order').over(window_client.rowsBetween(-n_quarter_nptb_pull, -1))
).withColumn(
    'total_client_net_sales_last_quarters',
    f.sum('total_client_net_sales').over(window_client.rowsBetween(-n_quarter_nptb_pull, -1))
).withColumn(
    'total_client_profit_sales_last_quarters',
    f.sum('total_client_profit_sales').over(window_client.rowsBetween(-n_quarter_nptb_pull, -1))
).drop('placed_order')

In [85]:
transactions_per_client.filter(
    f.col("_id") == working_ids[1]
).orderBy(
    "_id", "_observ_end_dt"
).show(50, truncate=False)

+--------------------------------------------------------------------------+--------------+----------------------+-------------------------+---------------------------------+------------------------------------+---------------------------------------+
|_id                                                                       |_observ_end_dt|total_client_net_sales|total_client_profit_sales|total_client_orders_last_quarters|total_client_net_sales_last_quarters|total_client_profit_sales_last_quarters|
+--------------------------------------------------------------------------+--------------+----------------------+-------------------------+---------------------------------+------------------------------------+---------------------------------------+
|00000E2B-FD56-4F34-A54C-159E564F5F79__FF8A2477-4270-4547-B4CB-5706EA4479A0|2023-01-01    |173.0434055328369     |133.9241008758545        |NULL                             |NULL                                |NULL                                   |
|00000E2B-FD56-4F34-A54C-159E564F5F79__FF8A2477-4270-4547-B4CB-5706EA4479A0|2023-04-01    |305.3913059234619     |264.34729385375977       |1                                |173.0434055328369                   |133.9241008758545                      |
|00000E2B-FD56-4F34-A54C-159E564F5F79__FF8A2477-4270-4547-B4CB-5706EA4479A0|2023-07-01    |NULL                  |NULL                     |2                                |478.4347114562988                   |398.27139472961426                     |
|00000E2B-FD56-4F34-A54C-159E564F5F79__FF8A2477-4270-4547-B4CB-5706EA4479A0|2023-10-01    |NULL                  |NULL                     |2                                |478.4347114562988                   |398.27139472961426                     |
|00000E2B-FD56-4F34-A54C-159E564F5F79__FF8A2477-4270-4547-B4CB-5706EA4479A0|2024-01-01    |286.9599914550781     |77.85639953613281        |2                                |478.4347114562988                   |398.27139472961426                     |
|00000E2B-FD56-4F34-A54C-159E564F5F79__FF8A2477-4270-4547-B4CB-5706EA4479A0|2024-04-01    |NULL                  |NULL                     |2                                |592.35129737854                     |342.2036933898926                      |
|00000E2B-FD56-4F34-A54C-159E564F5F79__FF8A2477-4270-4547-B4CB-5706EA4479A0|2024-07-01    |NULL                  |NULL                     |1                                |286.9599914550781                   |77.85639953613281                      |
|00000E2B-FD56-4F34-A54C-159E564F5F79__FF8A2477-4270-4547-B4CB-5706EA4479A0|2024-10-01    |NULL                  |NULL                     |1                                |286.9599914550781                   |77.85639953613281                      |
|00000E2B-FD56-4F34-A54C-159E564F5F79__FF8A2477-4270-4547-B4CB-5706EA4479A0|2025-01-01    |NULL                  |NULL                     |1                                |286.9599914550781                   |77.85639953613281                      |
|00000E2B-FD56-4F34-A54C-159E564F5F79__FF8A2477-4270-4547-B4CB-5706EA4479A0|2025-04-01    |NULL                  |NULL                     |0                                |NULL                                |NULL                                   |
|00000E2B-FD56-4F34-A54C-159E564F5F79__FF8A2477-4270-4547-B4CB-5706EA4479A0|2025-07-01    |NULL                  |NULL                     |0                                |NULL                                |NULL                                   |
+--------------------------------------------------------------------------+--------------+----------------------+-------------------------+---------------------------------+------------------------------------+---------------------------------------+

In [88]:
ftr_transactions = transactions_after_fst_trx.join(
    transactions_per_client,
    on=['_id', '_observ_end_dt'],
    how='left'
).withColumn(
    'last_transaction_quarter',
    f.when(
        f.col('total_product_val').isNotNull(),
        f.col('_observ_end_dt')
    ).otherwise(None)
).withColumn(
    'last_transaction_quarter',
    f.last('last_transaction_quarter', ignorenulls=True).over(window_client_product.rowsBetween(Window.unboundedPreceding, -1))
).withColumn(
    'total_product_val_last_order',
    f.last('total_product_val', ignorenulls=True).over(window_client_product.rowsBetween(Window.unboundedPreceding, -1))
).withColumn(
    'total_profit_product_val_last_order',
    f.last('total_profit_product_val', ignorenulls=True).over(window_client_product.rowsBetween(Window.unboundedPreceding, -1))
).withColumn(
    'units_last_order',
    f.last('product_qty', ignorenulls=True).over(window_client_product.rowsBetween(Window.unboundedPreceding, -1))
).withColumn(
    'quarters_from_last_order', #months passed since last order
    f.months_between(f.col('_observ_end_dt'),f.col('last_transaction_quarter')) / 3
).withColumn(
    'quarters_between_order', #only exists for months where order was placed
    f.when(
        f.col('total_product_val').isNotNull(),
        f.months_between(f.col('_observ_end_dt'), f.col('last_transaction_quarter')) / 3
    ).otherwise(None)
).withColumn(
    'avg_units_per_order_last_quarters',
    f.mean('product_qty').over(window_client_product.rowsBetween(-n_quarter_nptb_pull, -1))
).withColumn(
    'avg_quarters_between_orders', 
    f.mean('quarters_between_order').over(window_client_product.rowsBetween(-n_quarter_nptb_pull, -1))
).withColumn(
    'n_orders_sku_last_quarters',
    f.count('total_product_val').over(window_client_product.rowsBetween(-n_quarter_nptb_pull, -1))
).withColumn(
    'net_sales_sku_last_quarters', 
    f.sum('total_product_val').over(window_client_product.rowsBetween(-n_quarter_nptb_pull, -1))
).withColumn(
    'profit_sales_sku_last_quarters',
    f.sum('total_profit_product_val').over(window_client_product.rowsBetween(-n_quarter_nptb_pull, -1))
).withColumn(
    'sales_contribution_net',
    f.col('net_sales_sku_last_quarters') / f.col('total_client_net_sales_last_quarters')
).withColumn(
    'sales_contribution_catalog',
    f.col('profit_sales_sku_last_quarters') / f.col('total_client_profit_sales_last_quarters')
).withColumn(
    'repetition_rate',
    f.col('n_orders_sku_last_quarters') / f.col('total_client_orders_last_quarters')
).withColumn(
    'days_expected_breakage',
    f.col('units_last_order') / (f.col('avg_units_per_order_last_quarters') / f.col('avg_quarters_between_orders'))
).withColumn(
    'breakage_rate',
    f.col('quarters_from_last_order') / f.col('days_expected_breakage')
).withColumn(
    'adjusted_breakage_rate',
    f.when(
        f.col('breakage_rate') >= 1,
        f.col('breakage_rate')
    ).otherwise(0.1)
).withColumn(
    'prioritization_index',
    (f.col('quarters_from_last_order') / f.col('avg_quarters_between_orders')) * f.col('sales_contribution_catalog') * f.col('repetition_rate'))

In [89]:
ftr_transactions.show()

+--------------------+--------------+--------------------+--------------------+--------------------+----------------+-----------+------------------+------------------------+----------------------+-------------------------+---------------------------------+------------------------------------+---------------------------------------+------------------------+----------------------------+-----------------------------------+----------------+------------------------+----------------------+---------------------------------+---------------------------+--------------------------+---------------------------+------------------------------+----------------------+--------------------------+------------------+----------------------+-------------+----------------------+--------------------+
|                 _id|_observ_end_dt|          product_id|         customer_id| customer_vehicle_id|product_category|product_qty| total_product_val|total_profit_product_val|total_client_net_sales|total_client_profit_sales|total_client_orders_last_quarters|total_client_net_sales_last_quarters|total_client_profit_sales_last_quarters|last_transaction_quarter|total_product_val_last_order|total_profit_product_val_last_order|units_last_order|quarters_from_last_order|quarters_between_order|avg_units_per_order_last_quarters|avg_quarters_between_orders|n_orders_sku_last_quarters|net_sales_sku_last_quarters|profit_sales_sku_last_quarters|sales_contribution_net|sales_contribution_catalog|   repetition_rate|days_expected_breakage|breakage_rate|adjusted_breakage_rate|prioritization_index|
+--------------------+--------------+--------------------+--------------------+--------------------+----------------+-----------+------------------+------------------------+----------------------+-------------------------+---------------------------------+------------------------------------+---------------------------------------+------------------------+----------------------------+-----------------------------------+----------------+------------------------+----------------------+---------------------------------+---------------------------+--------------------------+---------------------------+------------------------------+----------------------+--------------------------+------------------+----------------------+-------------+----------------------+--------------------+
|00019832-FF3F-4AF...|    2024-10-01|ENGINE FLUSH | EN...|00019832-FF3F-4AF...|311BFEC3-78AF-43B...|    ENGINE FLUSH|          1|             333.0|                   258.0|     887.5700120925903|        619.9633960723877|                                1|                  351.86000657081604|                      149.3139944076538|                    NULL|                        NULL|                               NULL|            NULL|                    NULL|                  NULL|                             NULL|                       NULL|                         0|                       NULL|                          NULL|                  NULL|                      NULL|               0.0|                  NULL|         NULL|                   0.1|                NULL|
|00019832-FF3F-4AF...|    2025-01-01|ENGINE FLUSH | EN...|                NULL|                NULL|            NULL|       NULL|              NULL|                    NULL|    176.00000095367432|       105.02370262145996|                                2|                  1239.4300186634064|                      769.2773904800415|              2024-10-01|                       333.0|                              258.0|               1|                     1.0|                  NULL|                              1.0|                       NULL|                         1|                      333.0|                         258.0|   0.26867188545191534|        0.3353796734348371|               0.5|                  NULL|         NULL|                   0.1|                NULL|
|00019832-FF3F-4AF...|    2025-04-01|ENGINE FLUSH | EN...|                NULL|                NULL|            NULL|       NULL|              NULL|                    NULL|                  NULL|                     NULL|                                2|                  1063.5700130462646|                      724.9870986938477|              2024-10-01|                       333.0|                              258.0|               1|                     2.0|                  NULL|                              1.0|                       NULL|                         1|                      333.0|                         258.0|   0.31309645431448874|       0.35586840160992983|               0.5|                  NULL|         NULL|                   0.1|                NULL|
|00019832-FF3F-4AF...|    2025-07-01|ENGINE FLUSH | EN...|                NULL|                NULL|            NULL|       NULL|              NULL|                    NULL|                  NULL|                     NULL|                                2|                  1063.5700130462646|                      724.9870986938477|              2024-10-01|                       333.0|                              258.0|               1|                     3.0|                  NULL|                              1.0|                       NULL|                         1|                      333.0|                         258.0|   0.31309645431448874|       0.35586840160992983|               0.5|                  NULL|         NULL|                   0.1|                NULL|
|0003B739-C676-444...|    2022-01-01|ENGINE OIL CHANGE...|0003B739-C676-444...|16153D50-AC6F-456...|   OIL SYNTHETIC|          4|220.86959838867188|      194.04559326171875|     332.1738929748535|        272.3510932922363|                             NULL|                                NULL|                                   NULL|                    NULL|                        NULL|                               NULL|            NULL|                    NULL|                  NULL|                             NULL|                       NULL|                         0|                       NULL|                          NULL|                  NULL|                      NULL|              NULL|                  NULL|         NULL|                   0.1|                NULL|
|0003B739-C676-444...|    2022-04-01|ENGINE OIL CHANGE...|                NULL|                NULL|            NULL|       NULL|              NULL|                    NULL|    139.13040161132812|       105.09369659423828|                                1|                   332.1738929748535|                      272.3510932922363|              2022-01-01|          220.86959838867188|                 194.04559326171875|               4|                     1.0|                  NULL|                              4.0|                       NULL|                         1|         220.86959838867188|            194.04559326171875|    0.6649216060016864|        0.7124832543025824|               1.0|                  NULL|         NULL|                   0.1|                NULL|
|0003B739-C676-444...|    2022-07-01|ENGINE OIL CHANGE...|0003B739-C676-444...|16153D50-AC6F-456...|   OIL SYNTHETIC|          4|156.52169799804688|      126.10890197753906|    156.52169799804688|       119.83190202713013|                                2|                  471.30429458618164|                      377.4447898864746|              2022-01-01|          220.86959838867188|                 194.04559326171875|               4|                     2.0|                   2.0|                              4.0|                       NULL|                         1|         220.86959838867188|            194.04559326171875|    0.4686348096670784|         0.514103250226563|               0.5|                  NULL|         NULL|                   0.1|                NULL|
|0003B739-C676-444...|    2022-10-01|ENGINE OIL CHANGE...|                NULL|                NULL|            NULL|       NULL|              NULL|                    NULL|    103.47830200195312|        66.10789823532104|                                3|                   627.8259925842285|                     497.27669191360474|              2022-07-01|          156.52169799804688|                 126.10890197753906|               4|                     1.0|                  NULL|                              4.0|                        2.0|                         2|         377.39129638671875|             320.1544952392578|    0.6011081109167176|        0.6438156069757648|0.6666666666666666|                   2.0|          0.5|                   0.1| 0.21460520232525493|
|0003B739-C676-444...|    2023-01-01|ENGINE OIL CHANGE...|                NULL|                NULL|            NULL|       NULL|              NULL|                    NULL|     146.9564971923828|       107.60669946670532|                                4|                   731.3042945861816|                      563.3845901489258|              2022-07-01|          156.52169799804688|                 126.10890197753906|               4|                     2.0|                  NULL|                              4.0|                        2.0|                         2|         377.39129638671875|             320.1544952392578|     0.516052345351357|           0.5682698831976|               0.5|                   2.0|          1.0|                   1.0|     0.2841349415988|
|0003B739-C676-444...|    2023-04-01|ENGINE OIL CHANGE...|                NULL|                NULL|            NULL|       NULL|              NULL|                    NULL|                  NULL|                     NULL|                                4|                   546.0868988037109|                      398.6401963233948|              2022-07-01|          156.52169799804688|                 126.10890197753906|               4|                     3.0|                  NULL|                              4.0|                        2.0|                         1|         156.52169799804688|            126.10890197753906|   0.28662415879401654|        0.3163476817958264|              0.25|                   2.0|          1.5|                   1.5|  0.1186303806734349|
|0003B739-C676-444...|    2023-07-01|ENGINE OIL CHANGE...|                NULL|                NULL|            NULL|       NULL|              NULL|                    NULL|     173.4781951904297|       118.53550243377686|                                3|                   406.9564971923828|                      293.5464997291565|              2022-07-01|          156.52169799804688|                 126.10890197753906|               4|                     4.0|                  NULL|                              4.0|                        2.0|                         1|         156.52169799804688|            126.10890197753906|    0.3846153067413825|       0.42960451612911293|0.3333333333333333|                   2.0|          2.0|                   2.0| 0.28640301075274194|
|0003B739-C676-444...|    2023-10-01|ENGINE OIL CHANGE...|0003B739-C676-444...|16153D50-AC6F-456...|   OIL SYNTHETIC|          4| 156.5218048095703|      123.92420196533203|     156.5218048095703|       117.43330192565918|                                3|                   423.9129943847656|                      292.2501001358032|              2022-07-01|          156.52169799804688|                 126.10890197753906|               4|                     5.0|                   5.0|                             NULL|                       NULL|                         0|                       NULL|                          NULL|                  NULL|                      NULL|               0.0|                  NULL|         NULL|                   0.1|                NULL|
|0003B739-C676-444...|    2024-01-01|ENGINE OIL CHANGE...|                NULL|                NULL|            NULL|       NULL|              NULL|                    NULL|     397.4022035598755|       271.53005290031433|                                3|                   476.9564971923828|                     343.57550382614136|              2023-10-01|           156.5218048095703|                 123.92420196533203|               4|                     1.0|                  NULL|                              4.0|                        5.0|                         1|          156.5218048095703|            123.92420196533203|   0.32816788476714354|        0.3606898646302825|0.3333333333333333|                   5.0|          0.2|                   0.1|0.024045990975352167|
|0003B739-C676-444...|    2024-04-01|ENGINE OIL CHANGE...|                NULL|                NULL|            NULL|       NULL|              NULL|                    NULL|     94.77999973297119|        54.03549909591675|                                3|                   727.4022035598755|                     507.49885725975037|              2023-10-01|           156.5218048095703|                 123.92420196533203|               4|                     2.0|                  NULL|                              4.0|                        5.0|                         1|          156.5218048095703|            123.92420196533203|   0.21517917328756944|       0.24418616947132274|0.3333333333333333|                   5.0|          0.4|                   0.1|  0.0325581559295097|
|0003B739-C676-444...|    2024-07-01|ENGINE OIL CHANGE...|                NULL|                NULL|            NULL|       NULL|              NULL|                    NULL|     94.77999973297119|        23.99729895591736|                                4|                   822.1822032928467|                      561.5343563556671|              2023-10-01|           156.5218048095703|                 123.92420196533203|               4|                     3.0|                  NULL|                              4.0|                        5.0|                         1|          156.5218048095703|            123.92420196533203|    0.1903736230031484|        0.2206885483723464|              0.25|                   5.0|          0.6|                   0.1|0.033103282255851955|
|0003B739-C676-444...|    2024-10-01|ENGINE OIL CHANGE...|                NULL|                NULL|            NULL|       NULL|              NULL|                    NULL|                  NULL|                     NULL|                                4|                   743.4840078353882|                      466.9961528778076|              2023-10-01|           156.5218048095703|                 123.92420196533203|               4|                     4.0|                  NULL|                              4.0|                        5.0|                         1|          156.5218048095703|            123.92420196533203|   0.21052477680760712|        0.2653645029014994|              0.25|                   5.0|          0.8|                   0.1| 0.05307290058029988|
|0003B739-C676-444...|    2025-01-01|ENGINE OIL CHANGE...|                NULL|                NULL|            NULL|       NULL|              NULL|                    NULL|     69.98999786376953|       21.059399366378784|                                3|                   586.9622030258179|                     349.56285095214844|              2023-10-01|           156.5218048095703|                 123.92420196533203|               4|                     5.0|                  NULL|                             NULL|                       NULL|                         0|                       NULL|                          NULL|                  NULL|                      NULL|               0.0|                  NULL|         NULL|                   0.1|                NULL|
|0003B739-C676-444...|    2025-04-01|ENGINE OIL CHANGE...|                NULL|                NULL|            NULL|       NULL|              NULL|                    NULL|                  NULL|                     NULL|                                3|                   259.5499973297119|                      99.09219741821289|              2023-10-01|           156.5218048095703|                 123.92420196533203|               4|                     6.0|                  NULL|                             NULL|                       NULL|                         0|                       NULL|                          NULL|                  NULL|                      NULL|               0.0|                  NULL|         NULL|                   0.1|                NULL|
|0003B739-C676-444...|    2025-07-01|ENGINE OIL CHANGE...|                NULL|                NULL|            NULL|       NULL|              NULL|                    NULL|                  NULL|                     NULL|                                2|                  164.76999759674072|                      45.05669832229614|              2023-10-01|           156.5218048095703|                 123.92420196533203|               4|                     7.0|                  NULL|                             NULL|                       NULL|                         0|                       NULL|                          NULL|                  NULL|                      NULL|               0.0|                  NULL|         NULL|                   0.1|                NULL|
|0003C91C-DA0D-4A8...|    2022-04-01|ENGINE OIL CHANGE...|0003C91C-DA0D-4A8...|72E79B76-2AAC-4CF...|   OIL SYNTHETIC|          5|272.17388916015625|      237.06390380859375|     360.8695869445801|        284.7490043640137|                             NULL|                                NULL|                                   NULL|                    NULL|                        NULL|                               NULL|            NULL|                    NULL|                  NULL|                             NULL|                       NULL|                         0|                       NULL|                          NULL|                  NULL|                      NULL|              NULL|                  NULL|         NULL|                   0.1|                NULL|
+--------------------+--------------+--------------------+--------------------+--------------------+----------------+-----------+------------------+------------------------+----------------------+-------------------------+---------------------------------+------------------------------------+---------------------------------------+------------------------+----------------------------+-----------------------------------+----------------+------------------------+----------------------+---------------------------------+---------------------------+--------------------------+---------------------------+------------------------------+----------------------+--------------------------+------------------+----------------------+-------------+----------------------+--------------------+
only showing top 20 rows

In [90]:
ftr_transactions.filter(
    f.col("_id") == working_ids[1]
).orderBy(
    "_id", "_observ_end_dt"
).show(50, truncate=False)

+--------------------------------------------------------------------------+--------------+----------------------------------------------------------------------+------------------------------------+------------------------------------+----------------+-----------+------------------+------------------------+----------------------+-------------------------+---------------------------------+------------------------------------+---------------------------------------+------------------------+----------------------------+-----------------------------------+----------------+------------------------+----------------------+---------------------------------+---------------------------+--------------------------+---------------------------+------------------------------+----------------------+--------------------------+---------------+----------------------+-------------+----------------------+--------------------+
|_id                                                                       |_observ_end_dt|product_id                                                            |customer_id                         |customer_vehicle_id                 |product_category|product_qty|total_product_val |total_profit_product_val|total_client_net_sales|total_client_profit_sales|total_client_orders_last_quarters|total_client_net_sales_last_quarters|total_client_profit_sales_last_quarters|last_transaction_quarter|total_product_val_last_order|total_profit_product_val_last_order|units_last_order|quarters_from_last_order|quarters_between_order|avg_units_per_order_last_quarters|avg_quarters_between_orders|n_orders_sku_last_quarters|net_sales_sku_last_quarters|profit_sales_sku_last_quarters|sales_contribution_net|sales_contribution_catalog|repetition_rate|days_expected_breakage|breakage_rate|adjusted_breakage_rate|prioritization_index|
+--------------------------------------------------------------------------+--------------+----------------------------------------------------------------------+------------------------------------+------------------------------------+----------------+-----------+------------------+------------------------+----------------------+-------------------------+---------------------------------+------------------------------------+---------------------------------------+------------------------+----------------------------+-----------------------------------+----------------+------------------------+----------------------+---------------------------------+---------------------------+--------------------------+---------------------------+------------------------------+----------------------+--------------------------+---------------+----------------------+-------------+----------------------+--------------------+
|00000E2B-FD56-4F34-A54C-159E564F5F79__FF8A2477-4270-4547-B4CB-5706EA4479A0|2023-01-01    |ENGINE OIL CHANGE | OIL | PETROMIN SUPER 10W30 ENGINE OIL             |00000E2B-FD56-4F34-A54C-159E564F5F79|FF8A2477-4270-4547-B4CB-5706EA4479A0|OIL             |4          |141.73910522460938|117.53910064697266      |173.0434055328369     |133.9241008758545        |NULL                             |NULL                                |NULL                                   |NULL                    |NULL                        |NULL                               |NULL            |NULL                    |NULL                  |NULL                             |NULL                       |0                         |NULL                       |NULL                          |NULL                  |NULL                      |NULL           |NULL                  |NULL         |0.1                   |NULL                |
|00000E2B-FD56-4F34-A54C-159E564F5F79__FF8A2477-4270-4547-B4CB-5706EA4479A0|2023-01-01    |LUBRICATE LOCKS, HINGES AND LATCHES | SERVICE | SERVICE               |00000E2B-FD56-4F34-A54C-159E564F5F79|FF8A2477-4270-4547-B4CB-5706EA4479A0|SERVICE         |1          |0.0               |0.0                     |173.0434055328369     |133.9241008758545        |NULL                             |NULL                                |NULL                                   |NULL                    |NULL                        |NULL                               |NULL            |NULL                    |NULL                  |NULL                             |NULL                       |0                         |NULL                       |NULL                          |NULL                  |NULL                      |NULL           |NULL                  |NULL         |0.1                   |NULL                |
|00000E2B-FD56-4F34-A54C-159E564F5F79__FF8A2477-4270-4547-B4CB-5706EA4479A0|2023-01-01    |OIL FILTER SERVICE | KIA-OIL FILTERS | ENGINE OIL FILTER              |00000E2B-FD56-4F34-A54C-159E564F5F79|FF8A2477-4270-4547-B4CB-5706EA4479A0|KIA-OIL FILTERS |1          |31.30430030822754 |16.385000228881836      |173.0434055328369     |133.9241008758545        |NULL                             |NULL                                |NULL                                   |NULL                    |NULL                        |NULL                               |NULL            |NULL                    |NULL                  |NULL                             |NULL                       |0                         |NULL                       |NULL                          |NULL                  |NULL                      |NULL           |NULL                  |NULL         |0.1                   |NULL                |
|00000E2B-FD56-4F34-A54C-159E564F5F79__FF8A2477-4270-4547-B4CB-5706EA4479A0|2023-04-01    |ENGINE OIL CHANGE | OIL SYNTHETIC | PETROMIN SUPER SYNTHETIC 5W30 - 1L|00000E2B-FD56-4F34-A54C-159E564F5F79|FF8A2477-4270-4547-B4CB-5706EA4479A0|OIL SYNTHETIC   |4          |274.0870056152344 |240.66299438476562      |305.3913059234619     |264.34729385375977       |1                                |173.0434055328369                   |133.9241008758545                      |NULL                    |NULL                        |NULL                               |NULL            |NULL                    |NULL                  |NULL                             |NULL                       |0                         |NULL                       |NULL                          |NULL                  |NULL                      |0.0            |NULL                  |NULL         |0.1                   |NULL                |
|00000E2B-FD56-4F34-A54C-159E564F5F79__FF8A2477-4270-4547-B4CB-5706EA4479A0|2023-04-01    |ENGINE OIL CHANGE | OIL | PETROMIN SUPER 10W30 ENGINE OIL             |NULL                                |NULL                                |NULL            |NULL       |NULL              |NULL                    |305.3913059234619     |264.34729385375977       |1                                |173.0434055328369                   |133.9241008758545                      |2023-01-01              |141.73910522460938          |117.53910064697266                 |4               |1.0                     |NULL                  |4.0                              |NULL                       |1                         |141.73910522460938         |117.53910064697266            |0.8190956759557809    |0.8776545810520657        |1.0            |NULL                  |NULL         |0.1                   |NULL                |
|00000E2B-FD56-4F34-A54C-159E564F5F79__FF8A2477-4270-4547-B4CB-5706EA4479A0|2023-04-01    |LUBRICATE LOCKS, HINGES AND LATCHES | SERVICE | SERVICE               |00000E2B-FD56-4F34-A54C-159E564F5F79|FF8A2477-4270-4547-B4CB-5706EA4479A0|SERVICE         |1          |0.0               |0.0                     |305.3913059234619     |264.34729385375977       |1                                |173.0434055328369                   |133.9241008758545                      |2023-01-01              |0.0                         |0.0                                |1               |1.0                     |1.0                   |1.0                              |NULL                       |1                         |0.0                        |0.0                           |0.0                   |0.0                       |1.0            |NULL                  |NULL         |0.1                   |NULL                |
|00000E2B-FD56-4F34-A54C-159E564F5F79__FF8A2477-4270-4547-B4CB-5706EA4479A0|2023-04-01    |OIL FILTER SERVICE | KIA-OIL FILTERS | ENGINE OIL FILTER              |00000E2B-FD56-4F34-A54C-159E564F5F79|FF8A2477-4270-4547-B4CB-5706EA4479A0|KIA-OIL FILTERS |1          |31.30430030822754 |23.68429946899414       |305.3913059234619     |264.34729385375977       |1                                |173.0434055328369                   |133.9241008758545                      |2023-01-01              |31.30430030822754           |16.385000228881836                 |1               |1.0                     |1.0                   |1.0                              |NULL                       |1                         |31.30430030822754          |16.385000228881836            |0.18090432404421905   |0.12234541894793433       |1.0            |NULL                  |NULL         |0.1                   |NULL                |
|00000E2B-FD56-4F34-A54C-159E564F5F79__FF8A2477-4270-4547-B4CB-5706EA4479A0|2023-07-01    |ENGINE OIL CHANGE | OIL SYNTHETIC | PETROMIN SUPER SYNTHETIC 5W30 - 1L|NULL                                |NULL                                |NULL            |NULL       |NULL              |NULL                    |NULL                  |NULL                     |2                                |478.4347114562988                   |398.27139472961426                     |2023-04-01              |274.0870056152344           |240.66299438476562                 |4               |1.0                     |NULL                  |4.0                              |NULL                       |1                         |274.0870056152344          |240.66299438476562            |0.5728827759611042    |0.6042688417232458        |0.5            |NULL                  |NULL         |0.1                   |NULL                |
|00000E2B-FD56-4F34-A54C-159E564F5F79__FF8A2477-4270-4547-B4CB-5706EA4479A0|2023-07-01    |ENGINE OIL CHANGE | OIL | PETROMIN SUPER 10W30 ENGINE OIL             |NULL                                |NULL                                |NULL            |NULL       |NULL              |NULL                    |NULL                  |NULL                     |2                                |478.4347114562988                   |398.27139472961426                     |2023-01-01              |141.73910522460938          |117.53910064697266                 |4               |2.0                     |NULL                  |4.0                              |NULL                       |1                         |141.73910522460938         |117.53910064697266            |0.29625589830882515   |0.2951231301127457        |0.5            |NULL                  |NULL         |0.1                   |NULL                |
|00000E2B-FD56-4F34-A54C-159E564F5F79__FF8A2477-4270-4547-B4CB-5706EA4479A0|2023-07-01    |LUBRICATE LOCKS, HINGES AND LATCHES | SERVICE | SERVICE               |NULL                                |NULL                                |NULL            |NULL       |NULL              |NULL                    |NULL                  |NULL                     |2                                |478.4347114562988                   |398.27139472961426                     |2023-04-01              |0.0                         |0.0                                |1               |1.0                     |NULL                  |1.0                              |1.0                        |2                         |0.0                        |0.0                           |0.0                   |0.0                       |1.0            |1.0                   |1.0          |1.0                   |0.0                 |
|00000E2B-FD56-4F34-A54C-159E564F5F79__FF8A2477-4270-4547-B4CB-5706EA4479A0|2023-07-01    |OIL FILTER SERVICE | KIA-OIL FILTERS | ENGINE OIL FILTER              |NULL                                |NULL                                |NULL            |NULL       |NULL              |NULL                    |NULL                  |NULL                     |2                                |478.4347114562988                   |398.27139472961426                     |2023-04-01              |31.30430030822754           |23.68429946899414                  |1               |1.0                     |NULL                  |1.0                              |1.0                        |2                         |62.60860061645508          |40.06929969787598             |0.13086132573007064   |0.1006080281640085        |1.0            |1.0                   |1.0          |1.0                   |0.1006080281640085  |
|00000E2B-FD56-4F34-A54C-159E564F5F79__FF8A2477-4270-4547-B4CB-5706EA4479A0|2023-10-01    |ENGINE OIL CHANGE | OIL SYNTHETIC | PETROMIN SUPER SYNTHETIC 5W30 - 1L|NULL                                |NULL                                |NULL            |NULL       |NULL              |NULL                    |NULL                  |NULL                     |2                                |478.4347114562988                   |398.27139472961426                     |2023-04-01              |274.0870056152344           |240.66299438476562                 |4               |2.0                     |NULL                  |4.0                              |NULL                       |1                         |274.0870056152344          |240.66299438476562            |0.5728827759611042    |0.6042688417232458        |0.5            |NULL                  |NULL         |0.1                   |NULL                |
|00000E2B-FD56-4F34-A54C-159E564F5F79__FF8A2477-4270-4547-B4CB-5706EA4479A0|2023-10-01    |ENGINE OIL CHANGE | OIL | PETROMIN SUPER 10W30 ENGINE OIL             |NULL                                |NULL                                |NULL            |NULL       |NULL              |NULL                    |NULL                  |NULL                     |2                                |478.4347114562988                   |398.27139472961426                     |2023-01-01              |141.73910522460938          |117.53910064697266                 |4               |3.0                     |NULL                  |4.0                              |NULL                       |1                         |141.73910522460938         |117.53910064697266            |0.29625589830882515   |0.2951231301127457        |0.5            |NULL                  |NULL         |0.1                   |NULL                |
|00000E2B-FD56-4F34-A54C-159E564F5F79__FF8A2477-4270-4547-B4CB-5706EA4479A0|2023-10-01    |LUBRICATE LOCKS, HINGES AND LATCHES | SERVICE | SERVICE               |NULL                                |NULL                                |NULL            |NULL       |NULL              |NULL                    |NULL                  |NULL                     |2                                |478.4347114562988                   |398.27139472961426                     |2023-04-01              |0.0                         |0.0                                |1               |2.0                     |NULL                  |1.0                              |1.0                        |2                         |0.0                        |0.0                           |0.0                   |0.0                       |1.0            |1.0                   |2.0          |2.0                   |0.0                 |
|00000E2B-FD56-4F34-A54C-159E564F5F79__FF8A2477-4270-4547-B4CB-5706EA4479A0|2023-10-01    |OIL FILTER SERVICE | KIA-OIL FILTERS | ENGINE OIL FILTER              |NULL                                |NULL                                |NULL            |NULL       |NULL              |NULL                    |NULL                  |NULL                     |2                                |478.4347114562988                   |398.27139472961426                     |2023-04-01              |31.30430030822754           |23.68429946899414                  |1               |2.0                     |NULL                  |1.0                              |1.0                        |2                         |62.60860061645508          |40.06929969787598             |0.13086132573007064   |0.1006080281640085        |1.0            |1.0                   |2.0          |2.0                   |0.201216056328017   |
|00000E2B-FD56-4F34-A54C-159E564F5F79__FF8A2477-4270-4547-B4CB-5706EA4479A0|2024-01-01    |BATTERY SERVICES | BATTERIES | ACDELCO 27-55                          |00000E2B-FD56-4F34-A54C-159E564F5F79|FF8A2477-4270-4547-B4CB-5706EA4479A0|BATTERIES       |1          |286.9599914550781 |77.85639953613281       |286.9599914550781     |77.85639953613281        |2                                |478.4347114562988                   |398.27139472961426                     |NULL                    |NULL                        |NULL                               |NULL            |NULL                    |NULL                  |NULL                             |NULL                       |0                         |NULL                       |NULL                          |NULL                  |NULL                      |0.0            |NULL                  |NULL         |0.1                   |NULL                |
|00000E2B-FD56-4F34-A54C-159E564F5F79__FF8A2477-4270-4547-B4CB-5706EA4479A0|2024-01-01    |ENGINE OIL CHANGE | OIL SYNTHETIC | PETROMIN SUPER SYNTHETIC 5W30 - 1L|NULL                                |NULL                                |NULL            |NULL       |NULL              |NULL                    |286.9599914550781     |77.85639953613281        |2                                |478.4347114562988                   |398.27139472961426                     |2023-04-01              |274.0870056152344           |240.66299438476562                 |4               |3.0                     |NULL                  |4.0                              |NULL                       |1                         |274.0870056152344          |240.66299438476562            |0.5728827759611042    |0.6042688417232458        |0.5            |NULL                  |NULL         |0.1                   |NULL                |
|00000E2B-FD56-4F34-A54C-159E564F5F79__FF8A2477-4270-4547-B4CB-5706EA4479A0|2024-01-01    |ENGINE OIL CHANGE | OIL | PETROMIN SUPER 10W30 ENGINE OIL             |NULL                                |NULL                                |NULL            |NULL       |NULL              |NULL                    |286.9599914550781     |77.85639953613281        |2                                |478.4347114562988                   |398.27139472961426                     |2023-01-01              |141.73910522460938          |117.53910064697266                 |4               |4.0                     |NULL                  |4.0                              |NULL                       |1                         |141.73910522460938         |117.53910064697266            |0.29625589830882515   |0.2951231301127457        |0.5            |NULL                  |NULL         |0.1                   |NULL                |

In [92]:
window_prioritization = Window.partitionBy(['_id', '_observ_end_dt']).orderBy(f.col("prioritization_index").desc())

ftr_transactions_filtered = ftr_transactions.filter(
    f.col("prioritization_index").isNotNull()
).withColumn(
    'ranking', 
    f.row_number().over(window_prioritization)
).filter(
    f.col("_observ_end_dt") >= new_date
).filter(
    f.col("total_client_orders_last_quarters") >= min_number_of_trx_for_recommendations
).filter(
    f.col("ranking") <= n_recommendations_pull
).withColumnRenamed(
    'product_id',
    'product_id_pull'
)

In [93]:
ftr_transactions_filtered.show(truncate=False)

+--------------------------------------------------------------------------+--------------+--------------------------------------------------------------------------------------------------------------------+-----------+-------------------+----------------+-----------+-----------------+------------------------+----------------------+-------------------------+---------------------------------+------------------------------------+---------------------------------------+------------------------+----------------------------+-----------------------------------+----------------+------------------------+----------------------+---------------------------------+---------------------------+--------------------------+---------------------------+------------------------------+----------------------+--------------------------+------------------+----------------------+------------------+----------------------+--------------------+-------+
|_id                                                                       |_observ_end_dt|product_id_pull                                                                                                     |customer_id|customer_vehicle_id|product_category|product_qty|total_product_val|total_profit_product_val|total_client_net_sales|total_client_profit_sales|total_client_orders_last_quarters|total_client_net_sales_last_quarters|total_client_profit_sales_last_quarters|last_transaction_quarter|total_product_val_last_order|total_profit_product_val_last_order|units_last_order|quarters_from_last_order|quarters_between_order|avg_units_per_order_last_quarters|avg_quarters_between_orders|n_orders_sku_last_quarters|net_sales_sku_last_quarters|profit_sales_sku_last_quarters|sales_contribution_net|sales_contribution_catalog|repetition_rate   |days_expected_breakage|breakage_rate     |adjusted_breakage_rate|prioritization_index|ranking|
+--------------------------------------------------------------------------+--------------+--------------------------------------------------------------------------------------------------------------------+-----------+-------------------+----------------+-----------+-----------------+------------------------+----------------------+-------------------------+---------------------------------+------------------------------------+---------------------------------------+------------------------+----------------------------+-----------------------------------+----------------+------------------------+----------------------+---------------------------------+---------------------------+--------------------------+---------------------------+------------------------------+----------------------+--------------------------+------------------+----------------------+------------------+----------------------+--------------------+-------+
|00022BBA-25EC-4F9B-8BA1-01AE8517C894__078394A3-C78C-4A09-A75D-C10DF05F29F2|2025-07-01    |ENGINE OIL CHANGE | OIL | SUPER PETROMIN 10W30 SL (6 X 4 LTR) CTN                                                   |NULL       |NULL               |NULL            |NULL       |NULL             |NULL                    |NULL                  |NULL                     |3                                |786.9700088500977                   |498.50100231170654                     |2025-01-01              |103.4800033569336           |73.87680053710938                  |4               |2.0                     |NULL                  |5.333333333333333                |1.0                        |3                         |396.5300064086914          |278.8452033996582             |0.5038692732243912    |0.5593673876412785        |1.0               |0.75                  |2.6666666666666665|2.6666666666666665    |1.118734775282557   |1      |
|00022BBA-25EC-4F9B-8BA1-01AE8517C894__078394A3-C78C-4A09-A75D-C10DF05F29F2|2025-07-01    |SERVICE CHARGES 10 SAR | SERVICE | SERVICE                                                                          |NULL       |NULL               |NULL            |NULL       |NULL             |NULL                    |NULL                  |NULL                     |3                                |786.9700088500977                   |498.50100231170654                     |2025-01-01              |17.399999618530273          |0.0                                |2               |2.0                     |NULL                  |1.6666666666666667               |1.0                        |3                         |43.499999046325684         |0.0                           |0.05527529455650651   |0.0                       |1.0               |1.2                   |1.6666666666666667|1.6666666666666667    |0.0                 |2      |
|00022BBA-25EC-4F9B-8BA1-01AE8517C894__078394A3-C78C-4A09-A75D-C10DF05F29F2|2025-07-01    |FILTER INSTALLATION | SERVICE | SERVICE                                                                             |NULL       |NULL               |NULL            |NULL       |NULL             |NULL                    |NULL                  |NULL                     |3                                |786.9700088500977                   |498.50100231170654                     |2025-01-01              |22.600000381469727          |0.0                                |2               |2.0                     |NULL                  |1.6666666666666667               |1.0                        |3                         |56.500000953674316         |0.0                           |0.07179435088794656   |0.0                       |1.0               |1.2                   |1.6666666666666667|1.6666666666666667    |0.0                 |3      |
|0006BB63-7519-4855-84DE-E1772D2BA0D6__AD820DCA-2494-4072-B290-E59B895B3EFA|2025-07-01    |ENGINE OIL CHANGE | OIL | PETROMIN SUPER 10W30 ENGINE OIL                                                           |NULL       |NULL               |NULL            |NULL       |NULL             |NULL                    |NULL                  |NULL                     |4                                |516.0699987411499                   |306.1761016845703                      |2024-10-01              |86.0                        |58.53960037231445                  |4               |3.0                     |NULL                  |4.0                              |1.5                        |2                         |172.0                      |118.53960037231445            |0.3332881206416955    |0.3871615051603103        |0.5               |1.5                   |2.0               |2.0                   |0.3871615051603103  |1      |
|0006BB63-7519-4855-84DE-E1772D2BA0D6__AD820DCA-2494-4072-B290-E59B895B3EFA|2025-07-01    |ENGINE OIL CHANGE | OIL | PETROMIN SUPER 10W30 1L                                                                   |NULL       |NULL               |NULL            |NULL       |NULL             |NULL                    |NULL                  |NULL                     |4                                |516.0699987411499                   |306.1761016845703                      |2025-04-01              |86.0                        |55.1431999206543                   |4               |1.0                     |NULL                  |4.0                              |2.0                        |2                         |163.38999938964844         |101.67639923095703            |0.3166043362106029    |0.33208470116229516       |0.5               |2.0                   |0.5               |0.1                   |0.08302117529057379 |2      |
|0006BB63-7519-4855-84DE-E1772D2BA0D6__AD820DCA-2494-4072-B290-E59B895B3EFA|2025-07-01    |MIGHTY OIL FILTER SERVICE | OIL FILTERS | OIL FILTER                                                                |NULL       |NULL               |NULL            |NULL       |NULL             |NULL                    |NULL                  |NULL                     |4                                |516.0699987411499                   |306.1761016845703                      |2025-01-01              |20.43000030517578           |16.16990089416504                  |1               |2.0                     |NULL                  |1.5                              |1.0                        |2                         |20.43000030517578          |7.530900955200195             |0.03958765352570524   |0.02459663217921137       |0.5               |0.6666666666666666    |3.0               |3.0                   |0.02459663217921137 |3      |
|0006BB63-7519-4855-84DE-E1772D2BA0D6__AD820DCA-2494-4072-B290-E59B895B3EFA|2025-07-01    |SERVICE CHARGES 10 SAR | SERVICE | SERVICE                                                                          |NULL       |NULL               |NULL            |NULL       |NULL             |NULL                    |NULL                  |NULL                     |4                                |516.0699987411499                   |306.1761016845703                      |2025-04-01              |8.779999732971191           |0.0                                |1               |1.0                     |NULL                  |1.25                             |1.0                        |4                         |43.8199987411499           |0.0                           |0.08491095945906577   |0.0                       |1.0               |0.8                   |1.25              |1.25                  |0.0                 |4      |
|00085B30-A09A-46C8-B764-FB2C0E54E7B8__65F49866-166A-438E-9AB4-1BD1C33070EB|2025-07-01    |ENGINE OIL CHANGE | OIL | PETROMIN ULTRA 7 20W50 ENGINE OIL                                                         |NULL       |NULL               |NULL            |NULL       |NULL             |NULL                    |NULL                  |NULL                     |3                                |939.3299989700317                   |462.3281989097595                      |2025-01-01              |212.0                       |135.25399780273438                 |10              |2.0                     |NULL                  |9.333333333333334                |1.3333333333333333         |3                         |544.0                      |332.2138023376465             |0.5791361934533038    |0.7185670333781442        |1.0               |1.4285714285714284    |1.4000000000000001|1.4000000000000001    |1.0778505500672164  |1      |
|00085B30-A09A-46C8-B764-FB2C0E54E7B8__65F49866-166A-438E-9AB4-1BD1C33070EB|2025-07-01    |ENGINE OIL CHANGE | OIL | PETROMIN SUPER ULTRA 7 20W50 SL (6X4 LTR) CTN                                             |NULL       |NULL               |NULL            |NULL       |NULL             |NULL                    |NULL                  |NULL                     |3                                |939.3299989700317                   |462.3281989097595                      |2024-10-01              |106.0                       |69.21299743652344                  |5               |3.0                     |NULL                  |4.5                              |1.0                        |2                         |166.0                      |100.14219665527344            |0.17672170609053023   |0.21660412860695935       |0.6666666666666666|1.1111111111111112    |2.6999999999999997|2.6999999999999997    |0.4332082572139187  |2      |
|00085B30-A09A-46C8-B764-FB2C0E54E7B8__65F49866-166A-438E-9AB4-1BD1C33070EB|2025-07-01    |ECOWASH GOLD SUV (SERVICE INCLUDE: ECO WASH EXTERI | CONSUMABLES | FOGG SANITIZING SOLUTION (FLD/FLV-05 500ML)      |NULL       |NULL               |NULL            |NULL       |NULL             |NULL                    |NULL                  |NULL                     |3                                |939.3299989700317                   |462.3281989097595                      |2024-10-01              |18.75                       |15.602399826049805                 |1               |3.0                     |NULL                  |1.5                              |1.0                        |2                         |56.25                      |46.807199478149414            |0.05988310823850798   |0.10124236330063348       |0.6666666666666666|0.6666666666666666    |4.5               |4.5                   |0.20248472660126696 |3      |
|00085B30-A09A-46C8-B764-FB2C0E54E7B8__65F49866-166A-438E-9AB4-1BD1C33070EB|2025-07-01    |EXTRA | OIL | PETROMIN ULTRA 7 20W50 ENGINE OIL                                                                     |NULL       |NULL               |NULL            |NULL       |NULL             |NULL                    |NULL                  |NULL                     |3                                |939.3299989700317                   |462.3281989097595                      |2024-10-01              |20.0                        |12.325400352478027                 |1               |3.0                     |NULL                  |1.5                              |1.0                        |2                         |60.0                       |37.41790008544922             |0.06387531545440851   |0.08093363150611696       |0.6666666666666666|0.6666666666666666    |4.5               |4.5                   |0.16186726301223392 |4      |
|00085B30-A09A-46C8-B764-FB2C0E54E7B8__65F49866-166A-438E-9AB4-1BD1C33070EB|2025-07-01    |ECOWASH GOLD SUV (SERVICE INCLUDE: ECO WASH EXTERI | PE ENGINE CLEANING SERVICE | ENGINE CLEANING FOAM-DR. O SERVICE|NULL       |NULL               |NULL            |NULL       |NULL             |NULL                    |NULL                  |NULL                     |3                                |939.3299989700317                   |462.3281989097595                      |2024-10-01              |16.25                       |0.25                               |1               |3.0                     |NULL                  |1.5                              |1.0                        |2                         |48.75                      |0.75                          |0.05189869380670692   |0.0016222242159760415     |0.6666666666666666|0.6666666666666666    |4.5               |4.5                   |0.003244448431952083|5      |
|00085B30-A09A-46C8-B764-FB2C0E54E7B8__65F49866-166A-438E-9AB4-1BD1C33070EB|2025-07-01    |EXTRA | CONSUMABLES | PETROMIN AIR FRESHNER                                                                         |NULL       |NULL               |NULL            |NULL       |NULL             |NULL                    |NULL                  |NULL                     |3                                |939.3299989700317                   |462.3281989097595                      |2024-10-01              |0.0                         |0.0                                |1               |3.0                     |NULL                  |3.0                              |1.0                        |2                         |0.0                        |0.0                           |0.0                   |0.0                       |0.6666666666666666|0.3333333333333333    |9.0               |9.0                   |0.0                 |6      |
|00085B30-A09A-46C8-B764-FB2C0E54E7B8__65F49866-166A-438E-9AB4-1BD1C33070EB|2025-07-01    |SERVICE CHARGES 10 SAR | SERVICE | SERVICE                                                                          |NULL       |NULL               |NULL            |NULL       |NULL             |NULL                    |NULL                  |NULL                     |3                                |939.3299989700317                   |462.3281989097595                      |2025-01-01              |17.559999465942383          |0.0                                |2               |2.0                     |NULL                  |1.6666666666666667               |1.3333333333333333         |3                         |43.89999866485596          |0.0                           |0.04673543771942978   |0.0                       |1.0               |1.5999999999999996    |1.2500000000000002|1.2500000000000002    |0.0                 |7      |
|00085B30-A09A-46C8-B764-FB2C0E54E7B8__65F49866-166A-438E-9AB4-1BD1C33070EB|2025-07-01    |MIGHTY OIL FILTER SERVICE | OIL FILTERS | OIL FILTER                                                                |NULL       |NULL               |NULL            |NULL       |NULL             |NULL                    |NULL                  |NULL                     |3                                |939.3299989700317                   |462.3281989097595                      |2025-01-01              |20.43000030517578           |10.869900226593018                 |2               |2.0                     |NULL                  |2.6666666666666665               |1.3333333333333333         |3                         |20.43000030517578          |-23.690500259399414           |0.02174954523711275   |-0.051241737612512564     |1.0               |1.0                   |2.0               |2.0                   |-0.07686260641876885|8      |
|000864DC-AA3E-44A5-9018-549C04F85CCD__58CAD598-BAF5-4151-BD33-A5621CFE9AF0|2025-07-01    |ENGINE OIL CHANGE | OIL | SUPER PETROMIN 10W30 SL (6 X 4 LTR) CTN                                                   |NULL       |NULL               |NULL            |NULL       |NULL             |NULL                    |NULL                  |NULL                     |3                                |787.4800071716309                   |527.3406038284302                      |2025-01-01              |181.6500015258789           |122.44359970092773                 |8               |2.0                     |NULL                  |6.666666666666667                |1.0                        |3                         |476.4300079345703          |329.7112007141113             |0.6050058459842684    |0.6252338589527284        |1.0               |1.2                   |1.6666666666666667|1.6666666666666667    |1.2504677179054569  |1      |
|000864DC-AA3E-44A5-9018-549C04F85CCD__58CAD598-BAF5-4151-BD33-A5621CFE9AF0|2025-07-01    |OEM OIL FILTER SERVICE | HYUNDAI-OIL FILTERS | ENGINE OIL FILTER                                                    |NULL       |NULL               |NULL            |NULL       |NULL             |NULL                    |NULL                  |NULL                     |3                                |787.4800071716309                   |527.3406038284302                      |2025-01-01              |70.95999908447266           |47.61300086975098                  |2               |2.0                     |NULL                  |1.6666666666666667               |1.0                        |3                         |193.56999969482422         |135.86320304870605            |0.245809414755892     |0.2576384258339967        |1.0               |1.2                   |1.6666666666666667|1.6666666666666667    |0.5152768516679934  |2      |
|000864DC-AA3E-44A5-9018-549C04F85CCD__58CAD598-BAF5-4151-BD33-A5621CFE9AF0|2025-07-01    |EXTRA | OIL | PETROMIN SUPER 10W30 1L                                                                               |NULL       |NULL               |NULL            |NULL       |NULL             |NULL                    |NULL                  |NULL                     |3                                |787.4800071716309                   |527.3406038284302                      |2025-01-01              |40.0                        |24.57159996032715                  |2               |2.0                     |NULL                  |1.6666666666666667               |1.0                        |3                         |100.0                      |61.76620006561279             |0.12698735090325292   |0.1171277152132749        |1.0               |1.2                   |1.6666666666666667|1.6666666666666667    |0.2342554304265498  |3      |

In [96]:
out = ftr_transactions_filtered.orderBy(
    ['_id', 'product_id', '_observ_end_dt']
).select(
    '_id',
    'product_id_pull',
    'ranking'
)

In [97]:
out.show()

+--------------------+--------------------+-------+
|                 _id|     product_id_pull|ranking|
+--------------------+--------------------+-------+
|00002C41-103F-448...|TYRE SALES 17 INC...|      1|
|00007206-C3D7-423...|AIR FILTER SERVIC...|      2|
|00007206-C3D7-423...|ENGINE OIL CHANGE...|      1|
|00007206-C3D7-423...|MIGHTY OIL FILTER...|      3|
|00007206-C3D7-423...|SERVICE CHARGES 1...|      4|
|000083D3-935E-4E8...|AIR FILTER SERVIC...|      3|
|000083D3-935E-4E8...|ENGINE OIL CHANGE...|      1|
|000083D3-935E-4E8...|ENGINE OIL CHANGE...|      4|
|000083D3-935E-4E8...|OIL FILTER SERVIC...|      2|
|000083D3-935E-4E8...|TOP UP SERVICE | ...|      5|
|00009C4B-0D0D-479...|ENGINE OIL CHANGE...|      1|
|00009C4B-0D0D-479...|EXTRA | OIL | PET...|      3|
|00009C4B-0D0D-479...|OEM OIL FILTER SE...|      2|
|00009C4B-0D0D-479...|OIL FILTER SERVIC...|      4|
|00009C4B-0D0D-479...|SERVICE CHARGES 1...|      5|
|00022BBA-25EC-4F9...|ENGINE OIL CHANGE...|      1|
|00022BBA-25EC-4F9...|FILTER INSTALLATI...|      3|
|00022BBA-25EC-4F9...|SERVICE CHARGES 1...|      2|
|000293FE-CFD5-447...|ENGINE OIL CHANGE...|      1|
|000293FE-CFD5-447...|ENGINE OIL CHANGE...|      3|
+--------------------+--------------------+-------+
only showing top 20 rows

# Push

## Prepare Data

In [111]:
push_transactions = int_transactions.filter(
    ~f.col('product_id').isin(products_to_drop_push)
)

initial_date_n_quarters_before = pd.to_datetime(last_date) - relativedelta(months=n_quarter_nptb_push * 3)

push_transactions_grouped = push_transactions.filter(
    f.col('_observ_end_dt') >= initial_date_n_quarters_before
).groupBy(
    ['_id', 'product_id']
).agg(
    f.countDistinct('_observ_end_dt').alias('orders')
).filter(
    f.col('orders') > minimum_orders_to_be_considered
)

## Create Sparse Matrix

In [112]:
push_transactions_grouped.show(truncate=False)

+--------------------------------------------------------------------------+--------------------------------------------------------------------------------+------+
|_id                                                                       |product_id                                                                      |orders|
+--------------------------------------------------------------------------+--------------------------------------------------------------------------------+------+
|F7946ACB-C79A-42CF-8867-BDBCF8E3313F__34372926-971C-4848-89B3-E93D9C89FDCE|ENGINE OIL CHANGE | OIL SYNTHETIC | CASTROL 10W40SYN OIL                        |5     |
|1C47FFB6-A79F-408D-9A77-8D5C7E6A17FD__7B4B979F-3BE7-4281-B2D4-2A1309578A88|ENGINE OIL CHANGE | OIL SYNTHETIC | PETROMIN A-1 SUPER SYNTHETIC 5W-30 (6X4 LTR)|3     |
|D0B32CDC-5020-4077-AE4E-5D7906E983BA__527EE273-4AE9-4CA4-9B8F-E3823EFE74E5|ENGINE OIL CHANGE | OIL | FLEETMASTER LD API CH4 SAE 15W40                      |7     |
|4975BA51-C3E6-4A4D-8AED-C9DB3376D41C__B62E058E-83C6-4A23-AE78-F91D4F921E10|GASKET  | TOYOTA-OIL FILTERS | TOYOTA-GASKET-DRAIN PLUG                         |7     |
|EF8F7F6F-45AC-49AD-A516-6D1F31532EBF__865B15B4-436B-4F94-BCDB-A3A216228ABA|OEM OIL FILTER SERVICE | OIL FILTERS | OIL FILTER ISUZU D-MAX                   |7     |
|6C2D6B46-4897-479D-A089-EB72CCD5403B__454EC387-BCA3-4B99-B25B-EF3446FD23DB|EXTRA | OIL SYNTHETIC | PETROMIN SUPER SYNTHETIC 5W30 - 1L                      |3     |
|AAA50D94-AD64-46B5-A609-A97AF31C386D__70F51D31-A377-42D8-A605-1B24EE89839D|MIGHTY OIL FILTER SERVICE | OIL FILTERS | OIL FILTER                            |4     |
|B9344D87-0824-4E6C-BCB4-1B306F81D7B4__230E61A1-467F-4710-A762-95835AB0957C|ENGINE OIL CHANGE | OIL | PETROMIN SUPER 10W30 ENGINE OIL                       |3     |
|31A9D08F-0D20-4721-9707-00FBA7D8D23F__2A6C5993-54B1-45A3-94E2-C92843A88F7F|MIGHTY OIL FILTER SERVICE | OIL FILTERS | OIL FILTER                            |4     |
|DFF79BE5-463A-4E36-9894-D993F8F00035__761CBCF2-D258-4390-AC4B-CB7CC247211F|DRAIN PLUG WASHER - REPLACE | MAZDA-DRAIN PLUGS | DRAIN PLUG WASHER             |4     |
|51D9B26F-4E78-4C9F-8338-D9A0E81D57D2__2B70AD81-3134-47E5-B380-7EAC3D32F558|MIGHTY OIL FILTER SERVICE | OIL FILTERS | OIL FILTER                            |5     |
|CE97F80A-D85D-4D35-A4BA-71AC96CE6EE2__D0E79B97-29C4-47D3-867B-838D019FA7BD|ENGINE OIL CHANGE | OIL | PETROMIN SUPER 10W30 ENGINE OIL                       |7     |
|674B40D3-C694-40C7-BF04-7B3001377788__137256F2-7B09-4A41-B7A4-778BD15CD3DF|MIGHTY OIL FILTER SERVICE | OIL FILTERS | OIL FILTER                            |5     |
|24417971-217A-44E6-AF75-8150A24548AA__E3B02E99-F4F0-444E-B9AE-4D499C34BBAB|ENGINE OIL CHANGE | OIL | PETROMIN SUPER 10W30 ENGINE OIL                       |4     |
|3082FA52-E4C0-4862-B511-C81004D7D105__ECB4F4CD-DD3B-429D-9F97-D09968333479|OEM OIL FILTER SERVICE | TOYOTA-OIL FILTERS | OIL FILTER                        |3     |
|0E2CC8AE-7BA2-4C05-AABC-036A1B5F29D5__B059670A-AE38-4E54-BCD4-DC56D92A7537|OEM OIL FILTER SERVICE | NISSAN-OIL FILTERS | OIL FILTER                        |5     |
|73E0A6C5-203C-4043-9E03-95E53E8E3814__4F53039D-4CAE-460F-AA93-133736948F76|MIGHTY OIL FILTER SERVICE | OIL FILTERS | OIL FILTER                            |6     |
|C0E45346-4FCB-4129-BBE2-2F69EBC21704__7B5A6753-81C6-41F0-8D7E-67CB29F4252C|ENGINE OIL CHANGE | OIL SYNTHETIC | PETROMIN A-1 SUPER SYNTHETIC 5W-30 (6X4 LTR)|4     |
|89F10D2E-297C-47A1-92AB-434C27CA2437__1AB6DD95-47BC-4724-99FB-EFB38430CB2C|ENGINE OIL CHANGE | OIL SYNTHETIC | PETROMIN SUPER SYNTHETIC 5W30 - 1L          |4     |
|7F74E6E5-58B1-4F20-BEED-7DF93DEF12D5__01ACC7AB-D2A1-460F-AC05-9F6740EF8A60|MULTIPOINT INSPECTION | SERVICE | SERVICE                                       |7     |
+--------------------------------------------------------------------------+--------------------------------------------------------------------------------+------+
only showing top 20 rows

In [113]:
push_transactions_grouped.count()

1307992

In [122]:
push_transactions_grouped = push_transactions_grouped.withColumn(
    "user",
    f.hash("_id")
).withColumn(
    "item",
    f.hash("product_id")
)

In [118]:
from pyspark import ml

In [127]:
als_model = ml.recommendation.ALS(maxIter=40, rank=3, alpha=0.17, regParam=0.08, userCol="user", itemCol="item", ratingCol="orders")

als = als_model.fit(push_transactions_grouped)

In [130]:
push_transactions_grouped.filter(
    f.col("product_id").contains("SERVICE")
).orderBy("orders").select("product_id").distinct().show(truncate=False)

+--------------------------------------------------------------------------------------------------------------+
|product_id                                                                                                    |
+--------------------------------------------------------------------------------------------------------------+
|OEM OIL FILTER SERVICE | NISSAN-OIL FILTERS | OIL FILTER                                                      |
|MULTIPOINT INSPECTION | SERVICE | SERVICE                                                                     |
|OEM OIL FILTER SERVICE | GEELY-OIL FILTERS | OIL FILTER                                                       |
|AIR FILTER SERVICES | NISSAN-AIR FILTERS | AIR CLEANER ELEMENT                                                |
|OIL FILTER SERVICE | HYUNDAI-OIL FILTERS | HYUNDAI --- ENGINE OIL FILTER                                      |
|TOP UP SERVICE | GEAR OIL | PETROMIN GEAR OIL EP 140                                                          |
|MIGHTY OIL FILTER SERVICE | OIL FILTERS | AC DELCO---OIL FILTER HYUNDAIACCENT I (X-3) | VERNA1994-10          |
|OEM OIL FILTER SERVICE | OIL FILTERS | OIL FILTER                                                             |
|CABIN AIR FILTER SERVICES | HYUNDAI-CABIN AIR FILTERS | CABIN AIR FILTER                                      |
|ECOWASH GOLD SMALL&MEDIUM CARS  (SERVICE INCLUDES: | CONSUMABLES | FOGG SANITIZING SOLUTION (FLD/FLV-05 500ML)|
|CABIN AIR FILTER SERVICES | MG-SPARK PLUGS | MG---CABIN FILTER                                                |
|CABIN AIR FILTER SERVICES | KIA-CABIN AIR FILTERS | KIA ---CABIN AIR FILTER                                   |
|OIL FILTER SERVICE | OIL FILTERS | OIL FILTER--JEEP--GRAND CHEROKEE                                           |
|CABIN AIR FILTER SERVICES | KIA-CABIN AIR FILTERS | CABIN AC FILTER                                           |
|OEM OIL FILTER SERVICE | OIL FILTERS | OIL FILTER--JEEP--GRAND CHEROKEE                                       |
|OEM OIL FILTER SERVICE | OIL FILTERS | OIL FILTER---FORD                                                      |
|SMALL CAR WASH FULL | SERVICE | SERVICE                                                                       |
|CHECK AND TIGHTEN ALL NUTS AND BOLTS | SERVICE | SERVICE                                                      |
|OEM OIL FILTER SERVICE | OIL FILTERS | AC DELCO---OIL FILTER TOYOTAFJ CRUISER (GSJ1_)2006-01                  |
|AIR FILTER SERVICES | HYUNDAI-AIR FILTERS | HYUNDAI --FILTER-AIR CLEANER                                      |
+--------------------------------------------------------------------------------------------------------------+
only showing top 20 rows

In [128]:
als.transform(push_transactions_grouped.select("_id", "user", "product_id", "item").filter("user == 874363871")).show(truncate=False)

+--------------------------------------------------------------------------+---------+--------------------------------------------------------------------------------+-----------+----------+
|_id                                                                       |user     |product_id                                                                      |item       |prediction|
+--------------------------------------------------------------------------+---------+--------------------------------------------------------------------------------+-----------+----------+
|1C47FFB6-A79F-408D-9A77-8D5C7E6A17FD__7B4B979F-3BE7-4281-B2D4-2A1309578A88|874363871|ENGINE OIL CHANGE | OIL SYNTHETIC | PETROMIN A-1 SUPER SYNTHETIC 5W-30 (6X4 LTR)|-517231769 |2.9886227 |
|1C47FFB6-A79F-408D-9A77-8D5C7E6A17FD__7B4B979F-3BE7-4281-B2D4-2A1309578A88|874363871|MIGHTY OIL FILTER SERVICE | OIL FILTERS | OIL FILTER                            |-1895223630|3.8800359 |
+--------------------------------------------------------------------------+---------+--------------------------------------------------------------------------------+-----------+----------+

In [ ]:
customer_index = {
    customer: index
    for index, customer in enumerate(push_transactions_grouped["_id"].unique())
}

item_index = {
    item: index for index, item in enumerate(push_transactions_grouped["product_id"].unique())
}

row_indices = [
    customer_index[customer] 
    for customer in push_transactions_grouped["_id"]
]
col_indices = [
    item_index[item]
    for item in push_transactions_grouped["product_id"]
]

index_customer = {
    index: customer
    for customer, index in customer_index.items()
}
index_item = {
    index: item 
    for item, index in item_index.items()
}

sparse_matrix = sp.coo_matrix(
    (list(push_transactions_grouped.orders.values), (row_indices, col_indices))
)
train_matrix = sparse_matrix.tocsr()

TypeError: 'Column' object is not callable

## Get Recommendations

In [ ]:
model = AlternatingLeastSquares(**als_params)
model.fit(train_matrix)

unique = set(row_indices)

total = len(unique)

rank_list = [i for i in range(1, recommendations_per_user + 1)]
usuarios = []
categorias = []
ranking = []
propensity = []

for user in tqdm.tqdm(unique):
    ids, scores = model.recommend(
        user,
        train_matrix[user],
        N=recommendations_per_user,
        filter_already_liked_items=True,  ## Recomienda solo prductos nuevos
    )

    item_names = [index_item[index] for index in ids]
    usuarios += [index_customer[user]] * recommendations_per_user
    categorias += item_names
    ranking += rank_list
    propensity += [i for i in scores]

recomendaciones_por_usuario = pd.DataFrame(
    {
        "_id": usuarios,
        "product_id_push": categorias,
        "ranking": ranking,
    }
)

# Results from pipeline

In [19]:
pull_df = pd.read_parquet("../data/05_model/next_product_to_buy/pull/nptb_pull_transaction_features")
push_df = pd.read_parquet("../data/05_model/next_product_to_buy/push/nptb_push_recommendations")

In [20]:
pull_df.head()

,_id,product_id_pull,ranking
0,0001DUD__966543715767,AIR FILTER SERVICES | TOYOTA-AIR FILTERS | TOY...,8
1,0001DUD__966543715767,CABIN AIR FILTER SERVICES | TOYOTA-CABIN AIR F...,3
2,0001DUD__966543715767,ENGINE FLUSH | ENGINE FLUSH | PETROMIN ENGINE ...,4
3,0001DUD__966543715767,ENGINE OIL CHANGE | OIL SYNTHETIC | PETROMIN A...,1
4,0001DUD__966543715767,ENGINE OIL CHANGE | OIL SYNTHETIC | PETROMIN S...,5

In [21]:
push_df.head()

,_id,product_id_push,ranking
0,7616AAB__966538316318,ENGINE OIL CHANGE | OIL SYNTHETIC | PETROMIN A...,1
1,7616AAB__966538316318,OEM OIL FILTER SERVICE | TOYOTA-OIL FILTERS | ...,2
2,7616AAB__966538316318,OEM OIL FILTER SERVICE | HYUNDAI-OIL FILTERS |...,3
3,7616AAB__966538316318,TOP UP SERVICE | BRAKE FLUID | PETROMIN SUPER ...,4
4,7616AAB__966538316318,ENGINE OIL CHANGE | OIL | PETROMIN SUPER 10W30 1L,5

In [22]:
pull_df["_id"].unique().shape, push_df["_id"].unique().shape,

((253858,), (561627,))

In [23]:
pull_df["product_id_pull"].unique().shape, push_df["product_id_push"].unique().shape,

((713,), (60,))

In [27]:
pull_df[pull_df["_id"] == "0001DUD__966543715767"]

,_id,product_id_pull,ranking
0,0001DUD__966543715767,AIR FILTER SERVICES | TOYOTA-AIR FILTERS | TOY...,8
1,0001DUD__966543715767,CABIN AIR FILTER SERVICES | TOYOTA-CABIN AIR F...,3
2,0001DUD__966543715767,ENGINE FLUSH | ENGINE FLUSH | PETROMIN ENGINE ...,4
3,0001DUD__966543715767,ENGINE OIL CHANGE | OIL SYNTHETIC | PETROMIN A...,1
4,0001DUD__966543715767,ENGINE OIL CHANGE | OIL SYNTHETIC | PETROMIN S...,5
5,0001DUD__966543715767,FUEL INJECTION SERVICES | FUEL INJECTION | FUE...,2
6,0001DUD__966543715767,OEM OIL FILTER SERVICE | TOYOTA-OIL FILTERS | ...,7
7,0001DUD__966543715767,POWER STEERING SERVICES | ADDITIVES | POWER ST...,6

In [26]:
push_df["product_id_push"].value_counts()[:50]

product_id_push
ENGINE OIL CHANGE | OIL SYNTHETIC | PETROMIN A-1 SUPER SYNTHETIC 5W-30 (6X4 LTR)                354362
LUBRICATE LOCKS, HINGES AND LATCHES | SERVICE | SERVICE                                         348359
ENGINE OIL CHANGE | OIL | FLEETMASTER LD API CH4 SAE 15W40                                      291802
OEM OIL FILTER SERVICE | TOYOTA-OIL FILTERS | TOYOTA-OIL FILTERS                                274636
MULTIPOINT INSPECTION | SERVICE | SERVICE                                                       268453
MIGHTY OIL FILTER SERVICE | OIL FILTERS | OIL FILTER                                            254328
ENGINE OIL CHANGE | OIL | PETROMIN SUPER ULTRA 7 20W50 SL (6X4 LTR) CTN                         244144
GASKET  | TOYOTA-OIL FILTERS | TOYOTA-GASKET-DRAIN PLUG                                         239315
EXTRA | OIL SYNTHETIC | PETROMIN SUPER SYNTHETIC 5W30 - 1L                                      223975
TOP UP SERVICE | BRAKE FLUID | PETROMIN SUPER BRAKE FLUID DOT-4                                 220643
OIL FILTER SERVICE | HYUNDAI-OIL FILTERS | ENGINE OIL FILTER                                    205843
OIL FILTER SERVICE | TOYOTA-OIL FILTERS | TOYOTA-OIL FILTERS                                    202549
OEM OIL FILTER SERVICE | OIL FILTERS | OIL FILTER                                               198606
OEM OIL FILTER SERVICE | HYUNDAI-OIL FILTERS | ENGINE OIL FILTER                                198112
PARKING BRAKE - ADJUST | NISSAN-MISCELLANEOUS | BRAKE CLEANER SPRAY                             198075
ENGINE OIL CHANGE | OIL | PETROMIN SUPER 10W30 1L                                               197548
DRAIN PLUG WASHER - REPLACE | NISSAN-MISCELLANEOUS | WASHER-DRAIN PLUG                          196401
CHECK AND TIGHTEN ALL NUTS AND BOLTS | SERVICE | SERVICE                                        192694
ENGINE OIL CHANGE | OIL SYNTHETIC | PETROMIN SUPER SYNTHETIC 5W30 - 1L                          179035
EXTRA | OIL | PETROMIN FLEET MASTER LD 15W40 CH4                                                176110
ENGINE OIL CHANGE | OIL | PETROMIN FLEET MASTER LD 15W40 CH4                                    134560
ENGINE OIL CHANGE | OIL SYNTHETIC | PETROMIN SYNTHETIC HYBRID 5W20                              128939
ENGINE OIL CHANGE | OIL | PETROMIN SUPER 10W30 ENGINE OIL                                       127230
EXTRA | CONSUMABLES | PETROMIN AIR FRESHNER                                                      93873
OIL FILTER SERVICE | TOYOTA-OIL FILTERS | OIL FILTER                                             83519
OIL FILTER SERVICE | NISSAN-OIL FILTERS | OIL FILTER                                             76203
DRAIN PLUG SERVICES | MAZDA-DRAIN PLUGS | DRAIN PLUG                                             68884
ENGINE OIL CHANGE | OIL | TOYOTA 20W50 ENGINE OIL                                                54875
ENGINE OIL CHANGE | OIL | PETROMIN ULTRA 7 20W50 ENGINE OIL                                      50477
OEM OIL FILTER SERVICE | OIL FILTERS | OIL FILTER ISUZU D-MAX                                    42357
DRAIN PLUG WASHER - REPLACE | MAZDA-DRAIN PLUGS | DRAIN PLUG WASHER                              39180
OIL FILTER SERVICE | MAZDA-OIL FILTERS | ENGINE OIL FILTER                                       23313
OIL FILTER SERVICE | OIL FILTERS | OIL FILTER                                                    17373
EXTRA | OIL | PETROMIN ULTRA 7 20W50 ENGINE OIL                                                   9705
AIR FILTER SERVICES | AIR FILTERS | AIR FILTER ELEMENT                                             350
OIL FILTER SERVICE | OIL FILTERS | OIL FILTER ISUZU D-MAX                                          292
EXTRA | CONSUMABLES | PETROMIN CAR STICKER                                                          58
CABIN AIR FILTER SERVICES | CABIN AIR FILTERS | CABIN AIR FILTER                                    38
TOP UP SERVICE | COOLANTS | PETRO COOL 50                                                           11
TOP UP SERVICE | COOLANTS | COOLANT GREEN                                                           10
OIL FILTER SERVICE | KIA-OIL FILTERS | ENGINE OIL FILTER                                             4
MIGHTY OIL FILTER SERVICE | HYUNDAI-OIL FILTERS | ENGINE OIL FILTER                                  2
MIGHTY OIL FILTER SERVICE | OIL FILTERS | AC DELCO---OIL FILTER HYUNDAIGRAND SANTA F?2014-12         2
OIL FILTER SERVICE | OIL FILTERS | OIL FILTERS                                                       2
OEM OIL FILTER SERVICE | OIL FILTERS | OIL FILTERS                                                   2
TOP UP SERVICE | GEAR OIL | GULF GEAR OIL EP 90                                                      2
OIL FILTER SERVICE | OIL FILTERS | OEM OIL FILTER FL 820-S / FL 2142                                 2
OEM OIL FILTER SERVICE | OIL FILTERS | OEM OIL FILTER FL 820-S / FL 2142                             2
OEM OIL FILTER SERVICE | HYUNDAI-OIL FILTERS | HYUN 26350-2S000                                      2
OEM OIL FILTER SERVICE | TOYOTA-OIL FILTERS | TOYOTA OIL FILTER                                      2
Name: count, dtype: int64