In [2]:
import pandas as pd
from pathlib import Path

In [5]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [3]:

folder_path = "/home/ammar/petromin/data/02_intermediate/int_transactions"

# Read all parquet files in the folder (ignores .crc automatically)
df = pd.read_parquet(folder_path, engine="pyarrow")

print(df.shape)
print(df.head())

(51193256, 29)
                         transaction_id                           customer_id  \
0  0000054F-98E7-4A1B-85E7-FF505021DB02  51392616-9B76-4435-8C0E-43C0139BCA1F
1  0000054F-98E7-4A1B-85E7-FF505021DB02  51392616-9B76-4435-8C0E-43C0139BCA1F
2  0000058D-4FEF-42C4-BF36-9FF2744953D0  AF8F3733-EE8E-493C-AD23-2F15BF80CF16
3  0000058D-4FEF-42C4-BF36-9FF2744953D0  AF8F3733-EE8E-493C-AD23-2F15BF80CF16
4  0000088D-5070-4C46-AC94-3B619CA713C2  0A4575B2-347C-490D-ABA2-C220BBA9D600

                    customer_vehicle_id                             branch_id  \
0  7272896E-F429-47A5-88F8-1195CE25FB9D  BBD69E26-7BE0-41D0-BC40-D395C7D1DEDF
1  7272896E-F429-47A5-88F8-1195CE25FB9D  BBD69E26-7BE0-41D0-BC40-D395C7D1DEDF
2  151779EE-F4CE-4F5B-9430-393D04006AAE  6A0C15EA-2F3C-4F05-99AE-8481109A13A1
3  151779EE-F4CE-4F5B-9430-393D04006AAE  6A0C15EA-2F3C-4F05-99AE-8481109A13A1
4  99A94E11-0B9E-4911-B9EF-6457667AE93F  AC98BF1B-85AD-4745-A759-E7D7652CA5EF

  transaction_dt             product_family product_category  \
0     2023-01-28          ENGINE OIL CHANGE    OIL SYNTHETIC
1     2023-01-28  MIGHTY OIL FILTER SERVICE      OIL FILTERS
2     2021-03-25          ENGINE OIL CHANGE    OIL SYNTHETIC
3     2021-03-25         OIL FILTER SERVICE      OIL FILTERS
4     2025-04-11           BATTERY SERVICES        BATTERIES

                 product_sub_category         product_code  \
0  PETROMIN SUPER SYNTHETIC 5W30 - 1L  PET A-1 SYN 5W30 1L
1                          OIL FILTER                M3614
2  PETROMIN SUPER SYNTHETIC 5W30 - 1L  PET A-1 SYN 5W30 1L
3                          OIL FILTER          90915-YZZE1
4                  ACDELCO NX110-5LMF   ACDELCO-NX110-5LMF

                       package_name  ...  net_cost  discount_amount  \
0  PE SAR 180 SYNTHETIC OIL PACKAGE  ...   49.3032         0.000000
1                              NONE  ...    7.1958        35.652199
2            GOLD SYNTHETIC SERVICE  ...   18.6668         0.000000
3                              NONE  ...   11.7269         0.000000
4                              NONE  ...  263.8620         0.000000

   sales_amount_net  sales_amount_catalog  sales_amount  total_profit  \
0        269.565186            269.565186         310.0    220.261993
1          0.000000             35.652199           0.0     -7.195800
2        120.000000            120.000000         138.0    101.333199
3         20.869600             20.869600          24.0      9.142700
4        356.519989            356.519989         410.0     92.657997

   sales_amount_net_perc  has_discount  delta_mileage  delta_mileage_perc
0               0.710523             0         7943.0            0.099388
1                   -inf             1         7943.0            0.099388
2               0.734299             0        11640.0            0.082763
3               0.380946             0        11640.0            0.082763
4               0.225995             0         9656.0            0.065882

[5 rows x 29 columns]

In [6]:
df.head(2)

,transaction_id,customer_id,customer_vehicle_id,branch_id,transaction_dt,product_family,product_category,product_sub_category,product_code,package_name,product_id,is_fleet,is_pms,current_mileage,previous_mileage,new_customer,new_vehicle,warranty,quantity,net_cost,discount_amount,sales_amount_net,sales_amount_catalog,sales_amount,total_profit,sales_amount_net_perc,has_discount,delta_mileage,delta_mileage_perc
0,0000054F-98E7-4A1B-85E7-FF505021DB02,51392616-9B76-4435-8C0E-43C0139BCA1F,7272896E-F429-47A5-88F8-1195CE25FB9D,BBD69E26-7BE0-41D0-BC40-D395C7D1DEDF,2023-01-28,ENGINE OIL CHANGE,OIL SYNTHETIC,PETROMIN SUPER SYNTHETIC 5W30 - 1L,PET A-1 SYN 5W30 1L,PE SAR 180 SYNTHETIC OIL PACKAGE,ENGINE OIL CHANGE | OIL SYNTHETIC | PETROMIN S...,0,0,87862.0,79919.0,0,0,1,6.0,49.3032,0.000000,269.565186,269.565186,310.0,220.261993,0.710523,0,7943.0,0.099388
1,0000054F-98E7-4A1B-85E7-FF505021DB02,51392616-9B76-4435-8C0E-43C0139BCA1F,7272896E-F429-47A5-88F8-1195CE25FB9D,BBD69E26-7BE0-41D0-BC40-D395C7D1DEDF,2023-01-28,MIGHTY OIL FILTER SERVICE,OIL FILTERS,OIL FILTER,M3614,NONE,MIGHTY OIL FILTER SERVICE | OIL FILTERS | OIL ...,0,0,87862.0,79919.0,0,0,1,1.0,7.1958,35.652199,0.000000,35.652199,0.0,-7.195800,-inf,1,7943.0,0.099388

In [ ]:
# open /home/ammar/petromin/data/01_raw/transactions_origin.parquet
raw_df = pd.read_parquet("/home/ammar/petromin/data/01_raw/transactions_origin.parquet", engine="pyarrow")
print(raw_df.shape)
# raw_df.head()

(51193256, 29)

NameError: name 'printraw_df' is not defined

In [9]:
raw_df['ServiceItemGroupDefaultName'].nunique()

103

In [10]:
raw_df['ServiceName'].nunique()

345

In [8]:
raw_df.head()

,InvoiceID,CustomerID,CustomerVehicleID,BranchID,InvoiceDate,ServiceName,ServiceItemGroupDefaultName,ServiceItemDefaultName,ServiceItemCode,ServicePackageName,sku,IsFleet,IsPMS,WorkOrderMileage,PreviousMileage,NewCustomer,NewVehicle,Warranty,ItemBaseQuantity,ServiceItemCostAmount,InvoiceTotalDiscountAmount,InvoiceBeforeTaxAmount,InvoiceBeforeDiscountAmount,InvoiceTotalAmount,InvoiceGrossMargin,InvoiceGrossMargin_perc,hasDiscount,MileageBetweenVisits,MileageBetweenVisits_perc
0,0000054F-98E7-4A1B-85E7-FF505021DB02,51392616-9B76-4435-8C0E-43C0139BCA1F,7272896E-F429-47A5-88F8-1195CE25FB9D,BBD69E26-7BE0-41D0-BC40-D395C7D1DEDF,2023-01-28 22:36:40,Engine Oil change,Oil Synthetic,Petromin Super Synthetic 5w30 - 1L,PET A-1 SYN 5W30 1L,PE SAR 180 Synthetic Oil Package,Engine Oil change | Oil Synthetic | Petromin S...,0.0,0.0,87862.0,79919.0,0.0,0.0,1.0,6.0,49.3032,0.0,269.5652,269.5652,310.0,220.262,0.7105225806451613,0,7943.0,0.09938813048211315
1,0000054F-98E7-4A1B-85E7-FF505021DB02,51392616-9B76-4435-8C0E-43C0139BCA1F,7272896E-F429-47A5-88F8-1195CE25FB9D,BBD69E26-7BE0-41D0-BC40-D395C7D1DEDF,2023-01-28 22:36:40,Mighty Oil Filter Service,Oil Filters,Oil Filter,M3614,None,Mighty Oil Filter Service | Oil Filters | Oil ...,0.0,0.0,87862.0,79919.0,0.0,0.0,1.0,1.0,7.1958,35.6522,0.0,35.6522,0.0,-7.1958,-inf,1,7943.0,0.09938813048211315
2,0000058D-4FEF-42C4-BF36-9FF2744953D0,AF8F3733-EE8E-493C-AD23-2F15BF80CF16,151779EE-F4CE-4F5B-9430-393D04006AAE,6A0C15EA-2F3C-4F05-99AE-8481109A13A1,2021-03-25 14:02:18,Engine Oil change,Oil Synthetic,Petromin Super Synthetic 5w30 - 1L,PET A-1 SYN 5W30 1L,Gold Synthetic Service,Engine Oil change | Oil Synthetic | Petromin S...,1.0,0.0,152283.0,140643.0,0.0,0.0,0.0,4.0,18.6668,0.0,120.0,120.0,138.0,101.3332,0.7342985507246377,0,11640.0,0.0827627397026514
3,0000058D-4FEF-42C4-BF36-9FF2744953D0,AF8F3733-EE8E-493C-AD23-2F15BF80CF16,151779EE-F4CE-4F5B-9430-393D04006AAE,6A0C15EA-2F3C-4F05-99AE-8481109A13A1,2021-03-25 14:02:18,Oil Filter Service,Oil Filters,Oil Filter,90915-YZZE1,None,Oil Filter Service | Oil Filters | Oil Filter ...,1.0,0.0,152283.0,140643.0,0.0,0.0,0.0,1.0,11.7269,0.0,20.8696,20.8696,24.0,9.142699999999998,0.38094583333333326,0,11640.0,0.0827627397026514
4,0000088D-5070-4C46-AC94-3B619CA713C2,0A4575B2-347C-490D-ABA2-C220BBA9D600,99A94E11-0B9E-4911-B9EF-6457667AE93F,AC98BF1B-85AD-4745-A759-E7D7652CA5EF,2025-04-11 17:20:50,Battery Services,BATTERIES,ACDelco NX110-5LMF,ACDelco-NX110-5LMF,None,Battery Services | BATTERIES | ACDelco NX110-5...,0.0,0.0,156222.0,146566.0,0.0,0.0,0.0,1.0,263.862,0.0,356.52,356.52,410.0,92.65799999999996,0.2259951219512194,0,9656.0,0.06588158235880082